-- =========================================================================
-- ERP MODULAR SCHEMA: CRM, HRMS, PAYROLL, WHATSAPP & WORKFLOW
-- =========================================================================

-- 1. CONTACT MANAGEMENT (Unified Hub)
-- Standardizes Customers, Vendors, Leads, and Prospects
CREATE TABLE IF NOT EXISTS public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'customer', -- customer, vendor, lead, prospect
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company_name TEXT,
    job_title TEXT,
    website TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    status TEXT DEFAULT 'active',
    rating INTEGER DEFAULT 0,
    source TEXT, -- internal, web, referral, whatsapp
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CRM MODULE: DEALS & PIPELINES
CREATE TABLE IF NOT EXISTS public.crm_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT REFERENCES public.crm_pipelines(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    probability INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_deals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    stage_id BIGINT REFERENCES public.crm_stages(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    expected_closing DATE,
    priority TEXT DEFAULT 'medium', -- low, medium, high, critical
    status TEXT DEFAULT 'open', -- open, won, lost
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. HRMS MODULE: EMPLOYEES & ATTENDANCE
CREATE TABLE IF NOT EXISTS public.hrms_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    manager_id UUID, -- References users(id) or employees(id) later
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- App Login
    employee_code TEXT UNIQUE NOT NULL, -- e.g. EMP-101
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    department_id BIGINT REFERENCES public.hrms_departments(id) ON DELETE SET NULL,
    designation TEXT,
    date_of_joining DATE DEFAULT CURRENT_DATE,
    date_of_birth DATE,
    gender TEXT,
    blood_group TEXT,
    emergency_contact TEXT,
    status TEXT DEFAULT 'active', -- active, on-leave, resigned, terminated
    salary_basic DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    status TEXT DEFAULT 'present', -- present, absent, half-day, holiday
    ip_address TEXT,
    notes TEXT,
    UNIQUE(employee_id, date)
);

CREATE TABLE IF NOT EXISTS public.hrms_leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- sick, casual, annual
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. WHATSAPP & COMMUNICATIONS MODULE
CREATE TABLE IF NOT EXISTS public.wa_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    direction TEXT NOT NULL, -- inbound, outbound
    message TEXT NOT NULL,
    status TEXT DEFAULT 'sent', -- sent, delivered, read, failed
    external_id TEXT, -- Provider ID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. WORKFLOW ENGINE
CREATE TABLE IF NOT EXISTS public.wf_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    resource TEXT NOT NULL, -- sales_orders, hrms_leaves, etc.
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wf_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    approver_role TEXT, -- admin, manager, etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wf_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    resource_id UUID NOT NULL, -- ID of the order/leave/etc
    step_id BIGINT REFERENCES public.wf_steps(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL, -- approved, rejected, commented
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. HELPDESK MODULE
CREATE TABLE IF NOT EXISTS public.helpdesk_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT DEFAULT 'medium', -- low, medium, high, critical
    status TEXT DEFAULT 'open', -- open, in-progress, closed, cancelled
    assigned_to_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. SECURITY: RLS FOR MODULAR TABLES
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (
        SELECT tablename FROM pg_tables WHERE schemaname = 'public' 
        AND tablename IN (
            'contacts', 'crm_pipelines', 'crm_stages', 'crm_deals',
            'hrms_departments', 'hrms_employees', 'hrms_attendance', 'hrms_leaves',
            'wa_logs', 'wf_workflows', 'wf_steps', 'wf_logs', 'helpdesk_tickets'
        )
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
