-- =========================================================================
-- ECOMMERCE SAAS: FULL MASTER SCHEMA INIT SCRIPT
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. CORE ARCHITECTURE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subdomain TEXT UNIQUE NOT NULL,
    logo_url TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    gst_no TEXT,
    plan_id BIGINT, -- Links to system_plans
    plan TEXT DEFAULT 'starter', -- Legacy/Display tier
    plan_slug TEXT, -- Logical plan reference
    industry_type TEXT DEFAULT 'retail',
    user_id UUID, -- Original Creator/Owner
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_plan FOREIGN KEY (plan_id) REFERENCES public.system_plans(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    company_id BIGINT, -- Primary/Default Company
    is_super_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'admin',
    UNIQUE(company_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.system_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL, -- Logical identity node (slug)
    name TEXT NOT NULL,
    tagline TEXT,
    description TEXT,
    icon TEXT DEFAULT '🚀',
    color TEXT DEFAULT '#2563EB',
    color_from TEXT,
    color_to TEXT,
    route TEXT,
    dashboard_route TEXT,
    category TEXT DEFAULT 'operations',
    status TEXT DEFAULT 'live',
    features JSONB DEFAULT '[]', -- Feature Magnitude registry
    included_in_plans JSONB DEFAULT '[]', -- Authorized plans
    needs_template BOOLEAN DEFAULT false,
    is_core BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Who enabled it
    module_slug TEXT NOT NULL, -- Reference via SLUG for portability
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, module_slug)
);

CREATE TABLE IF NOT EXISTS public.user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    module_slug TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, user_id, module_slug)
);

-- -------------------------------------------------------------------------
-- 2. MASTER DATA TIER
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Creator
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES public.ecom_categories(id) ON DELETE SET NULL,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL,
    category TEXT, -- Legacy compatibility
    sku TEXT,
    rate DECIMAL(12,2) DEFAULT 0,
    price DECIMAL(12,2),
    description TEXT,
    image_url TEXT,
    is_ecommerce BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    is_best_seller BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sku TEXT,
    price DECIMAL(12,2),
    attributes_summary TEXT,
    stock_qty INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    subtitle TEXT,
    image_url TEXT NOT NULL,
    position TEXT DEFAULT 'hero',
    badge_text TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 3. ORDERS & FINANCIALS (Strict Audit)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Customer or Creator
    order_number TEXT UNIQUE NOT NULL,
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    shipping_address JSONB DEFAULT '{}',
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    shipping_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    payment_method TEXT,
    payment_status TEXT DEFAULT 'pending',
    payment_id TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT,
    variant_id BIGINT,
    product_name TEXT NOT NULL,
    variant_label TEXT,
    quantity INTEGER DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.ecom_order_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Admin actor
    status TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payment_gateways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Configuration Admin
    gateway TEXT NOT NULL,
    display_name TEXT,
    is_active BOOLEAN DEFAULT false,
    is_test_mode BOOLEAN DEFAULT true,
    config JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, gateway)
);

-- -------------------------------------------------------------------------
-- 4. WEBSITE MANAGER & CMS (Strictly Assigned)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Author
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content JSONB DEFAULT '[]',
    is_published BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, slug)
);

CREATE TABLE IF NOT EXISTS public.ecom_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    label TEXT NOT NULL,
    link_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    store_name TEXT,
    store_tagline TEXT,
    logo_url TEXT,
    primary_color TEXT DEFAULT '#000000',
    config JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id)
);

CREATE TABLE IF NOT EXISTS public.ecom_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Active User
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 5. HEADLESS API ARCHITECTURE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.headless_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Integrator
    api_key UUID DEFAULT gen_random_uuid(),
    screen_id TEXT NOT NULL,
    section_id TEXT NOT NULL,
    mapping_config JSONB NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, screen_id, section_id)
);

-- -------------------------------------------------------------------------
-- 6. SECURITY ENGINE (RLS & IDEMPOTENT POLICIES) - MOVED TO END
-- -------------------------------------------------------------------------

-- -------------------------------------------------------------------------
-- 7. SYSTEM SEED (CORE ONLY)
-- -------------------------------------------------------------------------
INSERT INTO public.system_modules (slug, name, is_core) VALUES 
('ecommerce', 'Ecommerce', true),
('crm', 'CRM', false),
('inventory', 'Inventory', false),
('landing-page', 'Website Manager', true)
ON CONFLICT (slug) DO NOTHING;

-- -------------------------------------------------------------------------
-- 8. PLATFORM TEMPLATES
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    industry TEXT DEFAULT 'multi-purpose',
    version TEXT DEFAULT '1.0.0',
    component_count INTEGER DEFAULT 12,
    preview_image TEXT,
    gallery_images TEXT[] DEFAULT '{}', -- 5 to 10 images for rich preview
    color TEXT,
    tags TEXT[],
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 9. SUBSCRIPTION & PACKAGE ENGINE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    price_monthly DECIMAL(12,2) DEFAULT 0,
    price_yearly DECIMAL(12,2) DEFAULT 0,
    features JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.system_plans (name, slug, price_monthly, features, sort_order) VALUES 
('Standard', 'standard', 29.00, '["Up to 5 Projects", "Basic Analytics", "Standard Templates", "Email Support"]', 1),
('Professional', 'professional', 99.00, '["Up to 20 Projects", "Advanced Analytics", "Premium Templates", "Priority Support", "Custom Domain"]', 2),
('Enterprise', 'enterprise', 299.00, '["Unlimited Projects", "Full White-label", "Custom Integrations", "Dedicated Account Manager", "SLA Guarantee"]', 3),
('Custom Application', 'custom', 0, '["Tailor-made Architecture", "On-premise Deployment", "Source Code Ownership", "24/7 Elite Support"]', 4)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.system_templates (folder, name, description, industry, version, component_count, preview_image, gallery_images, color, tags, is_active, sort_order) VALUES 
('amazon-style', 'Amazon Style', 'A robust, multi-category layout inspired by the world''s largest e-commerce platform. Best for megastores.', 'retail', '1.0.1', 24, 
 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?q=80&w=900', 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=900', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=900'],
 '#f97316', ARRAY['megastore', 'retail', 'amazon'], true, 1),

('fruitables', 'Fruitables Organic', 'Vibrant, fresh design perfect for organic groceries, fruit shops, and healthy food stores.', 'retail', '1.0.1', 12, 
 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=900', 'https://images.unsplash.com/photo-1466632311177-a3d1433f95e8?q=80&w=900', 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?q=80&w=900'],
 '#81c408', ARRAY['groceries', 'fresh', 'organic'], true, 2),

('modern-shop', 'Modern Shop', 'A sleek, minimalist design suitable for fashion, electronics, and dropshipping brands.', 'retail', '1.0.0', 16, 
 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=900', 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=900', 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=900'],
 '#000000', ARRAY['fashion', 'electronics', 'modern'], true, 3)
ON CONFLICT (folder) DO UPDATE SET is_active = EXCLUDED.is_active;

-- -------------------------------------------------------------------------
-- 9. SECURITY ENGINE (RLS & IDEMPOTENT POLICIES)
-- -------------------------------------------------------------------------
-- This ensures ALL tables created in the script above receive global access policies.
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    END LOOP;
END $$;

-- Universal Policy Builder
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        -- Drop global policies if they already exist
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Public Read" ON public.%I', tbl);
        
        -- Create open authenticated policy
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
        
        -- Create open anonymous policy for public interactions (like storefront reading products)
        EXECUTE format('CREATE POLICY "Global Public Read" ON public.%I FOR SELECT TO anon USING (true)', tbl);
    END LOOP;
END $$;
