-- =========================================================================
-- ERP CORE SCHEMA: SALES & PURCHASE MODULES (ERPNext/Odoo Style)
-- =========================================================================
-- This script adds the foundational parent-child table structures 
-- for professional grade ERP operations.

-- -------------------------------------------------------------------------
-- 1. SALES MODULE TABLES
-- -------------------------------------------------------------------------

-- SALES QUOTATIONS (Proposals)
CREATE TABLE IF NOT EXISTS public.sales_quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Created by
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. QUO-2026-001
    date DATE DEFAULT CURRENT_DATE,
    valid_until DATE,
    status TEXT DEFAULT 'draft', -- draft, sent, accepted, rejected, expired
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    notes TEXT,
    terms_and_conditions TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id UUID REFERENCES public.sales_quotations(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(5,2) DEFAULT 0, -- percentage
    amount DECIMAL(12,2) NOT NULL DEFAULT 0, -- (qty * price) + tax
    sort_order INTEGER DEFAULT 0
);

-- SALES ORDERS (Confirmed Sales)
CREATE TABLE IF NOT EXISTS public.sales_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    quotation_id UUID REFERENCES public.sales_quotations(id) ON DELETE SET NULL, -- Link back
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. ORD-2026-001
    date DATE DEFAULT CURRENT_DATE,
    delivery_date DATE,
    status TEXT DEFAULT 'draft', -- draft, on-hold, confirmed, closed, cancelled
    order_status TEXT DEFAULT 'to-deliver', -- to-deliver, delivered, partially-delivered
    billing_status TEXT DEFAULT 'to-invoice', -- to-invoice, invoiced, partially-invoiced
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

-- SALES INVOICES (Billing)
CREATE TABLE IF NOT EXISTS public.sales_invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. INV-2026-001
    date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    status TEXT DEFAULT 'draft', -- draft, unpaid, paid, overdue, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    payment_method TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id UUID REFERENCES public.sales_invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

-- -------------------------------------------------------------------------
-- 2. PURCHASE MODULE TABLES
-- -------------------------------------------------------------------------

-- PURCHASE REQUESTS (Internal Demand)
CREATE TABLE IF NOT EXISTS public.purchase_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. PREQ-2026-001
    date DATE DEFAULT CURRENT_DATE,
    required_by DATE,
    status TEXT DEFAULT 'draft', -- draft, pending-approval, approved, ordered, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID REFERENCES public.purchase_requests(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1
);

-- PURCHASE ORDERS (Vendor Procurement)
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. PUR-ORD-2026-001
    date DATE DEFAULT CURRENT_DATE,
    expected_delivery DATE,
    status TEXT DEFAULT 'draft', -- draft, confirmed, received, closed, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- PURCHASE BILLS (Vendor Invoices)
CREATE TABLE IF NOT EXISTS public.purchase_bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    bill_no TEXT NOT NULL, -- Vendor's own bill number
    reference_no TEXT UNIQUE NOT NULL, -- Our internal Ref: BILL-2026-001
    date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    status TEXT DEFAULT 'draft', -- draft, unpaid, paid, overdue
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id UUID REFERENCES public.purchase_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- -------------------------------------------------------------------------
-- 3. ENABLE RLS FOR NEW TABLES
-- -------------------------------------------------------------------------
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (
        SELECT tablename FROM pg_tables WHERE schemaname = 'public' 
        AND tablename IN (
            'sales_quotations', 'sales_quotation_items', 'sales_orders', 'sales_order_items',
            'sales_invoices', 'sales_invoice_items', 'purchase_requests', 'purchase_request_items',
            'purchase_orders', 'purchase_order_items', 'purchase_bills', 'purchase_bill_items'
        )
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
