-- =========================================================================
-- Smart Seyali: Integrated Business Modules Schema
-- Focus: CRM, Sales, Books, HRMS, Payroll
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. CRM MODULE (Leads, Contacts, Deals, Activities)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.crm_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Assigned To
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    phone TEXT,
    company_name TEXT,
    source TEXT, -- Website, Referral, etc.
    status TEXT DEFAULT 'New', -- New, Contacted, Qualified, Lost
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    phone TEXT,
    title TEXT,
    department TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    lead_id BIGINT REFERENCES public.crm_leads(id) ON DELETE SET NULL,
    contact_id BIGINT REFERENCES public.crm_contacts(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    pipeline_stage TEXT DEFAULT 'Discovery', -- Discovery, Proposal, Negotiation, Won, Lost
    expected_close_date DATE,
    probability INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Who did it
    link_type TEXT, -- 'lead', 'contact', 'deal'
    link_id BIGINT,
    type TEXT, -- Call, Email, Meeting, Note
    subject TEXT,
    description TEXT,
    due_date TIMESTAMPTZ,
    is_completed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 2. SALES MODULE (Quotations, Orders, Customers)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sales_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    display_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    billing_address JSONB DEFAULT '{}',
    shipping_address JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES public.sales_customers(id) ON DELETE CASCADE,
    deal_id BIGINT REFERENCES public.crm_deals(id) ON DELETE SET NULL, -- Integration Link
    quotation_number TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    expiry_date DATE,
    subtotal DECIMAL(15,2) DEFAULT 0,
    tax_total DECIMAL(15,2) DEFAULT 0,
    grand_total DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Draft', -- Draft, Sent, Accepted, Declined, Invoiced
    terms TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES public.sales_customers(id) ON DELETE CASCADE,
    quotation_id BIGINT REFERENCES public.sales_quotations(id) ON DELETE SET NULL,
    order_number TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    grand_total DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Pending', -- Pending, Shipped, Delivered, Invoiced
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 3. BOOKS (FINANCE) MODULE (Invoices, Expenses, Payments)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.books_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_id BIGINT REFERENCES public.sales_customers(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES public.sales_orders(id) ON DELETE SET NULL, -- Integration Link
    invoice_number TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    subtotal DECIMAL(15,2) DEFAULT 0,
    tax_total DECIMAL(15,2) DEFAULT 0,
    grand_total DECIMAL(15,2) DEFAULT 0,
    amount_paid DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Unpaid', -- Unpaid, Partial, Paid, Overdue, Cancelled
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.books_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    category TEXT, -- Rent, Utilities, Salary, etc.
    amount DECIMAL(15,2) NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    payee TEXT,
    payment_mode TEXT,
    reference_no TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 4. HRMS MODULE (Employees, Attendance, Leave)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.hrms_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Link to system user
    department_id BIGINT REFERENCES public.hrms_departments(id) ON DELETE SET NULL,
    employee_id TEXT UNIQUE,
    full_name TEXT NOT NULL,
    designation TEXT,
    email TEXT,
    phone TEXT,
    join_date DATE,
    salary DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'Active', -- Active, Terminated, Resigned
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ,
    check_out TIMESTAMPTZ,
    status TEXT DEFAULT 'Present', -- Present, Absent, Half-Day
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(employee_id, date)
);

CREATE TABLE IF NOT EXISTS public.hrms_leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id BIGINT REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    leave_type TEXT, -- Casual, Sick, Paid
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'Pending', -- Pending, Approved, Rejected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 5. ACCESS CONTROL (Module per User)
-- -------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    module_id BIGINT REFERENCES public.system_modules(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, user_id, module_id)
);

-- -------------------------------------------------------------------------
-- 6. SYSTEM MODULES SEED (Smart Seyali Modules)
-- -------------------------------------------------------------------------

INSERT INTO public.system_modules (name, slug, is_core, category, icon, tagline, description) VALUES
('CRM', 'crm', false, 'customer', '🎯', 'Convert leads into deals', 'Track leads, deals, and customer interactions across the full sales pipeline.'),
('Sales', 'sales', false, 'commerce', '💼', 'Quotations and orders', 'Manage quotations, sales orders, and customer payments seamlessly.'),
('Books', 'books', false, 'finance', '📊', 'Full-featured accounting', 'Ledgers, P&L, balance sheet, and compliance reporting in one place.'),
('HRMS', 'hrms', false, 'people', '👥', 'Employee management', 'Manage employee profiles, leave, attendance, and performance appraisals.'),
('Payroll', 'payroll', false, 'finance', '💰', 'Automate salaries', 'Process monthly payroll with automated calculations and statutory compliance.'),
('Landing Page Builder', 'landing-page', false, 'commerce', '🌐', 'Create marketing pages', 'Drag-and-drop builder for high-converting marketing landing pages.'),
('Ecommerce', 'ecommerce', true, 'commerce', '🛒', 'Sell online anywhere', 'Launch your online store with products, orders, and payment integrations.'),
('Invoices', 'invoicing', false, 'finance', '🧾', 'Professional billing', 'Create branded invoices, track payments, and send automated reminders.'),
('Ticket Booking', 'helpdesk', false, 'customer', '🎧', 'Customer support system', 'Manage support tickets, SLA tracking, and expert helpdesk operations.'),
('Hospital Management', 'hospital', false, 'operations', '🏥', 'Healthcare service ops', 'Manage patient records, doctor schedules, and medical billing.'),
('WhatsApp Integration', 'whatsapp', false, 'customer', '💬', 'Customer engagement', 'Automate messages and notifications via WhatsApp Business API.')
ON CONFLICT (slug) DO UPDATE SET 
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    icon = EXCLUDED.icon,
    tagline = EXCLUDED.tagline,
    description = EXCLUDED.description;

-- -------------------------------------------------------------------------
-- 7. RLS POLICIES FOR NEW TABLES
-- -------------------------------------------------------------------------

DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE ANY (ARRAY['crm_%', 'sales_%', 'books_%', 'hrms_%', 'user_modules'])) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Company Isolation" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Company Isolation" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
