/**
 * run_migration_14.cjs
 * Runs the ecom_templates migration using the Supabase JS client.
 * Uses zero external dependencies beyond @supabase/supabase-js.
 *
 * Usage:
 *   node run_migration_14.cjs
 */

const { createClient } = require('@supabase/supabase-js');

// ── Credentials (from .env) ──────────────────────────────────
const SUPABASE_URL = 'https://vxwjfonhadjjbdmkdrjc.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4d2pmb25oYWRqamJkbWtkcmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NTg0OTIsImV4cCI6MjA4NzIzNDQ5Mn0.lKrOXOLQtHDBhRgH6kz_t8admjaA_WR1bs_pIIwq0wM';

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

// ── Template seed data ────────────────────────────────────────
// Add one entry here per folder under /templates/
const TEMPLATES = [
    {
        folder: 'modern-shop',
        name: 'Modern Marketplace',
        description: 'Full-featured Flipkart-style layout with sticky header, mega menu, banner carousel, cart drawer, and multi-step checkout. Best for multi-category stores.',
        version: '1.0.0',
        preview_image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=900',
        color: '#2874f0',
        tags: ['featured', 'popular'],
        category: 'Marketplace',
        is_active: true,
        sort_order: 1
    }
];

async function run() {
    console.log('📦  Running migration 14: ecom_templates...\n');

    // Upsert into ecom_templates (table must exist via SQL migration first)
    const { data, error } = await supabase
        .from('ecom_templates')
        .upsert(TEMPLATES, { onConflict: 'folder' })
        .select();

    if (error) {
        console.error('❌  Migration failed:', error.message);
        console.log('\n💡  The ecom_templates table might not exist yet.');
        console.log('    Run the SQL below in Supabase Dashboard → SQL Editor:\n');
        console.log('─'.repeat(60));
        console.log(`
CREATE TABLE IF NOT EXISTS public.ecom_templates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder        TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    description   TEXT,
    version       TEXT DEFAULT '1.0.0',
    preview_image TEXT,
    color         TEXT DEFAULT '#14532d',
    tags          TEXT[] DEFAULT '{}',
    category      TEXT DEFAULT 'General',
    is_active     BOOLEAN DEFAULT true,
    sort_order    INTEGER DEFAULT 0,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ecom_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins Full Access" ON public.ecom_templates
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Public Read Active" ON public.ecom_templates
    FOR SELECT TO anon USING (is_active = true);
        `);
        console.log('─'.repeat(60));
        console.log('\n    Then re-run: node run_migration_14.cjs\n');
        process.exit(1);
    }

    console.log(`✅  Seeded ${data.length} template(s):\n`);
    data.forEach(t => console.log(`    [${t.sort_order}] ${t.folder.padEnd(20)} ${t.name} (v${t.version})`));
    console.log('\n🚀  Done! The onboarding page will now load templates from ecom_templates.\n');
}

run();
