-- =========================================================================
-- ULTIMATE ENTERPRISE ERP SAAS SCHEMA (Odoo/ERPNext Style)
-- =========================================================================
-- This script initializes the entire foundation for a multi-tenant
-- enterprise ecosystem including CRM, HRMS, SCM, Finance, and Automation.
-- =========================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- 0. EXTENSIONS & SETUP
-- ─────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────
-- 1. CORE SYSTEM & MULTI-TENANCY
-- ─────────────────────────────────────────────────────────────────────────

-- TENANTS (Top level isolation)
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    subdomain TEXT UNIQUE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COMPANIES (Internal organization nodes)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    tax_id TEXT,
    logo_url TEXT,
    website TEXT,
    currency_code TEXT DEFAULT 'INR',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COMPANY BRANCHES
CREATE TABLE IF NOT EXISTS public.company_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT, -- e.g. BR-001
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    phone TEXT,
    is_warehouse BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DEPARTMENTS
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.departments(id),
    name TEXT NOT NULL,
    code TEXT,
    manager_id UUID, -- References users(id) later
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DESIGNATIONS
CREATE TABLE IF NOT EXISTS public.designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    level INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USERS
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    password_hash TEXT,
    company_id BIGINT REFERENCES public.companies(id),
    branch_id BIGINT REFERENCES public.company_branches(id),
    is_super_admin BOOLEAN DEFAULT false,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ROLES & PERMISSIONS
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL, -- e.g. 'sales', 'hrms'
    action TEXT NOT NULL, -- e.g. 'create', 'view', 'delete'
    description TEXT,
    UNIQUE(module, action)
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    role_id BIGINT REFERENCES public.roles(id) ON DELETE CASCADE,
    permission_id BIGINT REFERENCES public.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY(role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES public.roles(id) ON DELETE CASCADE,
    PRIMARY KEY(user_id, role_id)
);

-- SYSTEM MANAGEMENT
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB,
    description TEXT
);

CREATE TABLE IF NOT EXISTS public.module_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    module_id TEXT NOT NULL,
    config JSONB DEFAULT '{}',
    is_enabled BOOLEAN DEFAULT true,
    UNIQUE(company_id, module_id)
);

-- LOGGING & AUDIT
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    resource_id TEXT,
    old_value JSONB,
    new_value JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 2. CONTACTS HUB (Unified Multi-Role Records)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'customer', -- customer, vendor, lead, employee
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    tax_id TEXT, -- GST/VAT
    company_name TEXT,
    website TEXT,
    status TEXT DEFAULT 'active',
    rating INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.contact_addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    type TEXT DEFAULT 'billing', -- shipping, billing, outlet
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    is_default BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.contact_bank_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    branch_name TEXT,
    is_default BOOLEAN DEFAULT false
);

-- ─────────────────────────────────────────────────────────────────────────
-- 3. PRODUCTS & UOM MATRIX
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.uom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.uoms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.uom_categories(id),
    name TEXT NOT NULL,
    ratio DECIMAL(12,4) DEFAULT 1.0, -- Relative to base UOM
    type TEXT DEFAULT 'bigger' -- smaller, reference, bigger
);

CREATE TABLE IF NOT EXISTS public.product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.product_categories(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL,
    uom_id BIGINT REFERENCES public.uoms(id),
    name TEXT NOT NULL,
    sku TEXT,
    barcode TEXT,
    type TEXT DEFAULT 'storable', -- storable, consumable, service
    description TEXT,
    image_url TEXT,
    standard_rate DECIMAL(15,2) DEFAULT 0, -- Cost
    sales_price DECIMAL(15,2) DEFAULT 0,
    weight DECIMAL(12,2),
    volume DECIMAL(12,2),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT,
    barcode TEXT,
    price_extra DECIMAL(15,2) DEFAULT 0,
    stock_qty DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. INVENTORY & WAREHOUSING
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.company_branches(id),
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    location_type TEXT DEFAULT 'internal',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stock_moves (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    reference_no TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL, -- incoming, outgoing, internal, adjustment
    warehouse_from_id BIGINT REFERENCES public.warehouses(id),
    warehouse_to_id BIGINT REFERENCES public.warehouses(id),
    status TEXT DEFAULT 'draft', -- draft, processed, cancelled
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stock_move_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    move_id UUID REFERENCES public.stock_moves(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL,
    uom_id BIGINT REFERENCES public.uoms(id),
    lot_no TEXT,
    serial_no TEXT
);

-- ─────────────────────────────────────────────────────────────────────────
-- 5. SALES & CRM (Revenue Engine)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sales_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Client
    branch_id BIGINT REFERENCES public.company_branches(id),
    reference_no TEXT UNIQUE NOT NULL, -- e.g. SO-2026-0001
    date DATE DEFAULT CURRENT_DATE,
    expected_delivery DATE,
    status TEXT DEFAULT 'draft', -- draft, confirmed, invoiced, delivered, cancelled
    subtotal DECIMAL(15,2) DEFAULT 0,
    tax_amount DECIMAL(15,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    grand_total DECIMAL(15,2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────
-- 6. PURCHASE (Procurement Cycle)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Vendor
    branch_id BIGINT REFERENCES public.company_branches(id),
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    expected_receipt DATE,
    status TEXT DEFAULT 'draft', -- draft, ordered, received, billed, cancelled
    grand_total DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────
-- 7. ACCOUNTING & FINANCE
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.accounts_chart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.accounts_chart(id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- asset, liability, equity, income, expense
    is_group BOOLEAN DEFAULT false,
    balance DECIMAL(15,2) DEFAULT 0,
    UNIQUE(company_id, code)
);

CREATE TABLE IF NOT EXISTS public.journals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    type TEXT DEFAULT 'general', -- sales, purchase, cash, bank
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id UUID REFERENCES public.journals(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES public.accounts_chart(id),
    contact_id UUID REFERENCES public.contacts(id),
    debit DECIMAL(15,2) DEFAULT 0,
    credit DECIMAL(15,2) DEFAULT 0,
    memo TEXT
);

-- ─────────────────────────────────────────────────────────────────────────
-- 8. HRMS & PAYROLL
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_salary_structures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    base_salary DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.hrms_employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Linked to unified contacts
    employee_code TEXT UNIQUE NOT NULL,
    department_id BIGINT REFERENCES public.departments(id),
    designation_id BIGINT REFERENCES public.designations(id),
    salary_structure_id BIGINT REFERENCES public.payroll_salary_structures(id),
    joining_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 9. PROJECTS & TASKS
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Client
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    start_date DATE,
    end_date DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to UUID REFERENCES public.users(id),
    priority TEXT DEFAULT 'medium',
    status TEXT DEFAULT 'todo',
    due_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 10. WORKFLOW ENGINE
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL, -- sales_orders, purchase_orders, hrms_leaves
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES public.workflows(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    required_role_id BIGINT REFERENCES public.roles(id)
);

CREATE TABLE IF NOT EXISTS public.approval_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL,
    resource_id UUID NOT NULL,
    workflow_id BIGINT REFERENCES public.workflows(id),
    current_step_id BIGINT REFERENCES public.workflow_steps(id),
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 11. SECURITY & RLS ENFORCEMENT
-- ─────────────────────────────────────────────────────────────────────────

DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Tenant Isolation Policy" ON public.%I', tbl);
        
        -- Global policy: Authenticated users can see records 
        -- Real production logic would check company_id/tenant_id 
        -- But for this MVP infrastructure, we enable full access to authenticated roles
        EXECUTE format('CREATE POLICY "Tenant Isolation Policy" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 12. INITIAL SYSTEM SEED
-- ─────────────────────────────────────────────────────────────────────────

-- Base UOMs
INSERT INTO public.uom_categories (name) VALUES ('Unit'), ('Weight'), ('Volume'), ('Time') ON CONFLICT DO NOTHING;
INSERT INTO public.uoms (category_id, name, ratio, type) VALUES 
((SELECT id FROM uom_categories WHERE name='Unit'), 'Nos', 1.0, 'reference'),
((SELECT id FROM uom_categories WHERE name='Weight'), 'Kg', 1.0, 'reference'),
((SELECT id FROM uom_categories WHERE name='Weight'), 'Gram', 0.001, 'smaller'),
((SELECT id FROM uom_categories WHERE name='Time'), 'Hour', 1.0, 'reference')
ON CONFLICT DO NOTHING;

-- Base Permissions
INSERT INTO public.permissions (module, action) VALUES 
('sales', 'create'), ('sales', 'view'), ('sales', 'delete'), ('sales', 'approve'),
('purchase', 'create'), ('purchase', 'view'), ('purchase', 'delete'),
('hrms', 'create'), ('hrms', 'view'),
('finance', 'create'), ('finance', 'post')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 13. WHATSAPP & META INTEGRATION (Bulk Messaging & Campaigns)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.whatsapp_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone_number_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    verify_token TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    whatsapp_account_id UUID REFERENCES public.whatsapp_accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- marketing, utility, authentication
    language TEXT DEFAULT 'en_US',
    components JSONB NOT NULL, -- Header, Body, Footer, Buttons
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    meta_template_id TEXT, -- Template ID from Meta
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    template_id UUID REFERENCES public.whatsapp_templates(id),
    audience_filter JSONB, -- Criteria for target contacts
    status TEXT DEFAULT 'draft', -- draft, scheduled, running, completed
    scheduled_at TIMESTAMPTZ,
    stats JSONB DEFAULT '{"sent": 0, "delivered": 0, "read": 0, "failed": 0}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id),
    campaign_id UUID REFERENCES public.whatsapp_campaigns(id),
    message_sid TEXT,
    status TEXT, -- sent, delivered, read, failed
    payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 14. HRMS EXTENSIONS: INDUCTION & ONBOARDING
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.hrms_induction_protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_onboarding_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_id BIGINT REFERENCES public.hrms_induction_protocols(id) ON DELETE CASCADE,
    task_name TEXT NOT NULL,
    mandatory BOOLEAN DEFAULT true,
    order_index INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.hrms_employee_induction (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    protocol_id BIGINT REFERENCES public.hrms_induction_protocols(id),
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed
    completion_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 15. PAYROLL ENGINE & PAYSLIPS
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- earning, deduction
    calculation_type TEXT NOT NULL, -- flat, percentage
    value DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.payroll_payslips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    basic_salary DECIMAL(15,2) DEFAULT 0,
    gross_earnings DECIMAL(15,2) DEFAULT 0,
    total_deductions DECIMAL(15,2) DEFAULT 0,
    net_salary DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'draft', -- draft, processed, paid, cancelled
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 16. E-COMMERCE & CATALOG MASTERS (Brands, Attributes, Variants)
-- ─────────────────────────────────────────────────────────────────────────

-- BRANDS
CREATE TABLE IF NOT EXISTS public.product_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    logo_url TEXT,
    website TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SUB-BRANDS
CREATE TABLE IF NOT EXISTS public.product_sub_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES public.product_brands(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ATTRIBUTES (Size, Color, Material, etc.)
CREATE TABLE IF NOT EXISTS public.product_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- e.g. 'Color'
    display_type TEXT DEFAULT 'text', -- text, swatches, dropdown
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ATTRIBUTE VALUES (Red, XL, Silk, etc.)
CREATE TABLE IF NOT EXISTS public.product_attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id BIGINT REFERENCES public.product_attributes(id) ON DELETE CASCADE,
    value TEXT NOT NULL, -- e.g. 'Red'
    meta_data JSONB, -- e.g. {"hex": "#FF0000"}
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LINK PRODUCTS TO BRANDS
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES public.product_brands(id);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sub_brand_id BIGINT REFERENCES public.product_sub_brands(id);

-- PRODUCT REVIEWS (Consumer Feedback Node)
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    is_verified_purchase BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'pending', -- pending, approved, hidden
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LINK VARIANTS TO ATTRIBUTE VALUES
CREATE TABLE IF NOT EXISTS public.product_variant_attribute_values (
    variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE CASCADE,
    attribute_value_id BIGINT REFERENCES public.product_attribute_values(id) ON DELETE CASCADE,
    PRIMARY KEY(variant_id, attribute_value_id)
);

-- RE-RUN RLS ENFORCEMENT LOOP
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Tenant Isolation Policy" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Tenant Isolation Policy" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
