-- SUBSCRIPTION & BILLING SCHEMA

CREATE TABLE IF NOT EXISTS public.subscription_plans (
    id TEXT PRIMARY KEY, -- e.g. 'starter', 'pro', 'enterprise'
    name TEXT NOT NULL,
    price_monthly DECIMAL(12,2) NOT NULL,
    price_yearly DECIMAL(12,2) NOT NULL,
    features JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    plan_id TEXT REFERENCES public.subscription_plans(id),
    status TEXT DEFAULT 'active', -- 'active', 'past_due', 'canceled', 'trial'
    billing_cycle TEXT DEFAULT 'monthly', -- 'monthly', 'yearly'
    current_period_start TIMESTAMPTZ DEFAULT NOW(),
    current_period_end TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id)
);

-- Seed Initial Plans
INSERT INTO public.subscription_plans (id, name, price_monthly, price_yearly, features) VALUES
('free', 'Starter / Free', 0, 0, '["Up to 50 Products", "Standard Checkout", "Basic Analytics", "Community Support"]'),
('pro', 'Business Pro', 2499, 24990, '["Unlimited Products", "Advanced SEO", "Custom Domain Support", "Priority Support", "Abandoned Cart Recovery"]'),
('enterprise', 'Institution / Enterprise', 9999, 99990, '["Multiple Storefronts", "Custom Integrations", "Dedicated Account Manager", "White-label Mobile App", "99.9% SLA"]')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name, 
    price_monthly = EXCLUDED.price_monthly, 
    price_yearly = EXCLUDED.price_yearly, 
    features = EXCLUDED.features;

-- RLS for Subscriptions
ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow Public View Plans" ON public.subscription_plans FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Full Access Auth Subscriptions" ON public.subscriptions FOR ALL TO authenticated USING (true) WITH CHECK (true);
