-- WEBSITE CONTENT TABLES

CREATE TABLE IF NOT EXISTS public.ecom_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content JSONB DEFAULT '{}',
    is_published BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, slug)
);

CREATE TABLE IF NOT EXISTS public.ecom_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    link_url TEXT NOT NULL,
    menu_type TEXT DEFAULT 'main', -- 'main', 'footer'
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.ecom_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecom_menus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Full Access Auth Pages" ON public.ecom_pages FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Auth Menus" ON public.ecom_menus FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Pages" ON public.ecom_pages FOR SELECT TO anon USING (is_published = true);
CREATE POLICY "Public Read Menus" ON public.ecom_menus FOR SELECT TO anon USING (true);
