-- ACTIVITY LOGS

CREATE TABLE IF NOT EXISTS public.ecom_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL, -- 'order_placed', 'product_updated', 'settings_changed'
    entity_type TEXT, -- 'order', 'product', 'settings'
    entity_id TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.ecom_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Full Access Auth Activities" ON public.ecom_activities FOR ALL TO authenticated USING (true) WITH CHECK (true);
