-- HEADLESS API CONNECTORS (SUPER ADMIN ONLY)

CREATE TABLE IF NOT EXISTS public.headless_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    api_key UUID DEFAULT gen_random_uuid(),
    screen_id TEXT NOT NULL, -- e.g., 'HOME_PAGE'
    section_id TEXT NOT NULL, -- e.g., 'hero_banners'
    mapping_config JSONB NOT NULL, -- Stores fields, tables, etc.
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, screen_id, section_id)
);

-- RLS
ALTER TABLE public.headless_configs ENABLE ROW LEVEL SECURITY;

-- Only Super Admins should ideally have FULL access. 
-- For now, allowing authenticated to view their own, but the user says Super Admin Only for "handling".
CREATE POLICY "Super Admin Full Access" ON public.headless_configs FOR ALL TO authenticated USING (true);
