-- PAYMENT GATEWAYS & ORDER ARCHITECTURE

CREATE TABLE IF NOT EXISTS public.payment_gateways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    gateway TEXT NOT NULL, -- 'razorpay', 'stripe', 'cod', etc.
    display_name TEXT,
    is_active BOOLEAN DEFAULT false,
    is_test_mode BOOLEAN DEFAULT true,
    config JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, gateway)
);

CREATE TABLE IF NOT EXISTS public.ecom_orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_number TEXT NOT NULL UNIQUE,
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    shipping_address JSONB DEFAULT '{}',
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    shipping_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    payment_method TEXT,
    payment_status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'failed', 'refunded'
    payment_id TEXT, -- External Gateway ID
    status TEXT DEFAULT 'pending', -- 'pending', 'confirmed', 'shipped', 'delivered', 'cancelled'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    product_id BIGINT,
    variant_id BIGINT,
    product_name TEXT,
    variant_label TEXT,
    quantity INTEGER DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_order_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.payment_gateways ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecom_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecom_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecom_order_timeline ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Full Access Auth Gateways" ON public.payment_gateways FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Auth Orders" ON public.ecom_orders FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Auth Order Items" ON public.ecom_order_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Full Access Auth Order Timeline" ON public.ecom_order_timeline FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Public can read gateways for checkout
CREATE POLICY "Public Read Gateways" ON public.payment_gateways FOR SELECT TO anon USING (is_active = true);
