-- 10_ADMIN_REFINEMENT_SUITE.sql
-- Consolidate missing tables and fix order generation logic for the Merchant Suite.

-- 1. ORDER NUMBER GENERATOR (Fixes null order_number constraint violation)
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.order_number IS NULL THEN
        NEW.order_number := 'ORD-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT), 1, 8));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_generate_order_number ON public.ecom_orders;
CREATE TRIGGER trg_generate_order_number
    BEFORE INSERT ON public.ecom_orders
    FOR EACH ROW
    EXECUTE FUNCTION public.generate_order_number();

-- 2. MISSING TABLES FOR REFINED MODULES

-- BLOG SYSTEM
CREATE TABLE IF NOT EXISTS public.ecom_blog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content TEXT,
    excerpt TEXT,
    image_url TEXT,
    author_name TEXT,
    is_published BOOLEAN DEFAULT true,
    published_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, slug)
);

-- COUPONS & DISCOUNTS
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL DEFAULT 'percentage', -- percentage, fixed, free_shipping, buy_x_get_y
    value DECIMAL(12,2) DEFAULT 0,
    min_order_amount DECIMAL(12,2) DEFAULT 0,
    max_discount DECIMAL(12,2),
    usage_limit INTEGER,
    used_count INTEGER DEFAULT 0,
    per_user_limit INTEGER DEFAULT 1,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, code)
);

-- OFFERS & CAMPAIGNS
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL DEFAULT 'flash_sale', -- flash_sale, bundle, flat_off, buy_x_get_y, category_deal
    discount_type TEXT DEFAULT 'percentage',
    discount_value DECIMAL(12,2) DEFAULT 0,
    badge_label TEXT,
    image_url TEXT,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SHIPPING ZONES
CREATE TABLE IF NOT EXISTS public.shipping_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    courier_partner TEXT,
    base_rate DECIMAL(12,2) DEFAULT 0,
    free_above DECIMAL(12,2),
    estimated_days TEXT,
    states TEXT[], -- Array of covered states
    pincodes TEXT[], -- Array of covered pincodes
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- PRODUCT REVIEWS
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    product_id BIGINT CHECK(product_id IS NOT NULL), -- Ensure product reference
    customer_name TEXT,
    customer_email TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    title TEXT,
    body TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    is_verified_purchase BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ABANDONED CARTS
CREATE TABLE IF NOT EXISTS public.abandoned_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    customer_name TEXT,
    customer_email TEXT,
    items JSONB DEFAULT '[]',
    cart_total DECIMAL(12,2) DEFAULT 0,
    recovery_email_sent BOOLEAN DEFAULT false,
    recovered BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS & ACCESS POLICIES (Idempotent Apply)
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN 
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename IN ('ecom_blog', 'coupons', 'offers', 'shipping_zones', 'product_reviews', 'abandoned_carts')
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Public Read" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Public Read" ON public.%I FOR SELECT TO anon USING (true)', tbl);
    END LOOP;
END $$;

-- 4. ADDITIONAL SETTINGS COLUMNS
ALTER TABLE public.ecom_settings 
ADD COLUMN IF NOT EXISTS whatsapp_number TEXT,
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS social_links JSONB DEFAULT '{}';

-- 5. REFUND SYSTEM
CREATE TABLE IF NOT EXISTS public.ecom_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    amount DECIMAL(12,2) NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending', -- pending, processed, rejected
    refund_method TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
