-- Migration 12: Create all missing tables for admin pages
-- Fixes: Offers, Coupons, Shipping Zones, Reviews, Refunds, Gallery

-- ── OFFERS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT DEFAULT 'flash_sale',      -- flash_sale | bundle_deal | flat_off | buy_x_get_y | category_deal
    discount_type TEXT DEFAULT 'percentage', -- percentage | flat
    discount_value DECIMAL(10,2) DEFAULT 0,
    badge_label TEXT,
    image_url TEXT,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── COUPONS ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    description TEXT,
    type TEXT DEFAULT 'percentage',      -- percentage | flat | free_shipping | buy_x_get_y
    value DECIMAL(10,2) DEFAULT 0,
    min_order_amount DECIMAL(10,2) DEFAULT 0,
    max_discount DECIMAL(10,2),
    usage_limit INTEGER,
    usage_count INTEGER DEFAULT 0,
    per_user_limit INTEGER DEFAULT 1,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, code)
);

-- ── SHIPPING ZONES ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.shipping_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    states TEXT[],
    pincodes TEXT[],
    base_rate DECIMAL(10,2) DEFAULT 0,
    free_above DECIMAL(10,2),
    estimated_days TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── PRODUCT REVIEWS ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    customer_name TEXT,
    customer_email TEXT,
    rating INTEGER DEFAULT 5,
    review TEXT,
    status TEXT DEFAULT 'pending',       -- pending | approved | rejected
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── REFUNDS ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE SET NULL,
    amount DECIMAL(10,2) NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'requested',     -- requested | approved | processed | rejected
    refund_method TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── MEDIA GALLERY ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ecom_gallery_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    tags TEXT[],
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_gallery_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    video_url TEXT NOT NULL,
    thumbnail_url TEXT,
    alt_text TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── RLS POLICIES (Permissive for now) ────────────────────────────
DO $$
DECLARE tbl TEXT;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'offers','coupons','shipping_zones','product_reviews',
        'refunds','ecom_gallery_images','ecom_gallery_videos'
    ]) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Public Read" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Public Read" ON public.%I FOR SELECT TO anon USING (true)', tbl);
    END LOOP;
END $$;
