-- Migration 13: Add missing columns to existing tables (safe ALTER TABLE)
-- Run this if tables already existed before migration 12

-- Fix offers table
ALTER TABLE public.offers
    ADD COLUMN IF NOT EXISTS image_url TEXT,
    ADD COLUMN IF NOT EXISTS discount_type TEXT DEFAULT 'percentage',
    ADD COLUMN IF NOT EXISTS discount_value DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS badge_label TEXT,
    ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;

-- Fix coupons table
ALTER TABLE public.coupons
    ADD COLUMN IF NOT EXISTS per_user_limit INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS max_discount DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS usage_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS valid_until TIMESTAMPTZ;

-- Fix shipping_zones table
ALTER TABLE public.shipping_zones
    ADD COLUMN IF NOT EXISTS states TEXT[],
    ADD COLUMN IF NOT EXISTS pincodes TEXT[],
    ADD COLUMN IF NOT EXISTS base_rate DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS free_above DECIMAL(10,2),
    ADD COLUMN IF NOT EXISTS estimated_days TEXT;

-- Fix ecom_banners table (from migration 11)
ALTER TABLE public.ecom_banners
    ADD COLUMN IF NOT EXISTS button_text TEXT,
    ADD COLUMN IF NOT EXISTS button_link TEXT,
    ADD COLUMN IF NOT EXISTS overlay_opacity INTEGER DEFAULT 40,
    ADD COLUMN IF NOT EXISTS text_color TEXT DEFAULT 'white',
    ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;

-- Ensure all new tables exist
CREATE TABLE IF NOT EXISTS public.ecom_gallery_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    tags TEXT[],
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_gallery_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    video_url TEXT NOT NULL,
    thumbnail_url TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    customer_name TEXT,
    customer_email TEXT,
    rating INTEGER DEFAULT 5,
    review TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE SET NULL,
    amount DECIMAL(10,2) NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'requested',
    refund_method TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Apply RLS to all new/modified tables
DO $$
DECLARE tbl TEXT;
BEGIN
    FOR tbl IN SELECT unnest(ARRAY[
        'offers','coupons','shipping_zones','product_reviews',
        'refunds','ecom_gallery_images','ecom_gallery_videos'
    ]) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Public Read" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Public Read" ON public.%I FOR SELECT TO anon USING (true)', tbl);
    END LOOP;
END $$;

-- ── COLLECTIONS TABLE ─────────────────────────────────────────────
-- Collections admin was throwing "table 'public.collections' not found"
CREATE TABLE IF NOT EXISTS public.collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    slug TEXT,
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Full Access" ON public.collections;
CREATE POLICY "Full Access" ON public.collections FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── ECOM_ORDERS: Add columns needed by enhanced checkout ──────────
ALTER TABLE public.ecom_orders
    ADD COLUMN IF NOT EXISTS customer_phone TEXT,
    ADD COLUMN IF NOT EXISTS shipping_amount DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS coupon_code TEXT;

