-- Migration 14: ecom_templates table
-- Central registry for all available storefront templates.
-- Source of truth for the onboarding template selector.
-- Replaces hardcoded template arrays in Onboarding.tsx and storefront.
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.ecom_templates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identity
    folder        TEXT NOT NULL UNIQUE,          -- Matches /templates/<folder> on disk
    name          TEXT NOT NULL,                 -- Display name shown in onboarding UI
    description   TEXT,                          -- Short description / tagline
    version       TEXT DEFAULT '1.0.0',          -- Semantic version

    -- UI / Preview
    preview_image TEXT,                          -- Hero thumbnail shown in the card
    color         TEXT DEFAULT '#14532d',        -- Brand accent color written to ecom_settings
    tags          TEXT[] DEFAULT '{}',           -- e.g. ARRAY['featured','popular','new']
    category      TEXT DEFAULT 'General',        -- Marketplace | Fashion | Electronics | etc.

    -- Availability
    is_active     BOOLEAN DEFAULT true,          -- Show in onboarding selector
    sort_order    INTEGER DEFAULT 0,             -- Lower = first in list

    -- Audit
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── Keep updated_at current ───────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_ecom_templates_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$;

DROP TRIGGER IF EXISTS trg_ecom_templates_updated_at ON public.ecom_templates;
CREATE TRIGGER trg_ecom_templates_updated_at
    BEFORE UPDATE ON public.ecom_templates
    FOR EACH ROW EXECUTE FUNCTION public.set_ecom_templates_updated_at();

-- ── Row Level Security ────────────────────────────────────────────────
ALTER TABLE public.ecom_templates ENABLE ROW LEVEL SECURITY;

-- Any authenticated user (admin) can manage templates
DROP POLICY IF EXISTS "Admins Full Access" ON public.ecom_templates;
CREATE POLICY "Admins Full Access"
    ON public.ecom_templates
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Public (anon) can read active templates for the onboarding page
DROP POLICY IF EXISTS "Public Read Active" ON public.ecom_templates;
CREATE POLICY "Public Read Active"
    ON public.ecom_templates
    FOR SELECT
    TO anon
    USING (is_active = true);

-- ── Seed initial templates from project /templates directory ──────────
-- Add one row per folder that exists under /templates/
INSERT INTO public.ecom_templates
    (folder, name, description, version, preview_image, color, tags, category, sort_order)
VALUES
    (
        'modern-shop',
        'Modern Marketplace',
        'Full-featured Flipkart-style layout with sticky header, mega menu, banner carousel, cart drawer, and multi-step checkout. Best for multi-category stores.',
        '1.0.0',
        'https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=900',
        '#2874f0',
        ARRAY['featured','popular'],
        'Marketplace',
        1
    )
ON CONFLICT (folder) DO UPDATE SET
    name          = EXCLUDED.name,
    description   = EXCLUDED.description,
    preview_image = EXCLUDED.preview_image,
    color         = EXCLUDED.color,
    tags          = EXCLUDED.tags,
    category      = EXCLUDED.category,
    updated_at    = NOW();

-- ── Verification ──────────────────────────────────────────────────────
SELECT folder, name, version, category, is_active
FROM   public.ecom_templates
ORDER  BY sort_order;
