-- Migration 15: User Permissions Table
-- Support for granular resource-level permissions for team members.

CREATE TABLE IF NOT EXISTS public.user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_user_id BIGINT REFERENCES public.company_users(id) ON DELETE CASCADE,
    resource TEXT NOT NULL, -- e.g., 'products', 'orders', etc.
    action TEXT NOT NULL DEFAULT 'manage', -- 'read', 'write', 'manage'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_user_id, resource, action)
);

-- Enable RLS
ALTER TABLE public.user_permissions ENABLE ROW LEVEL SECURITY;

-- Global Access Policy
DROP POLICY IF EXISTS "Global Full Access" ON public.user_permissions;
CREATE POLICY "Global Full Access" ON public.user_permissions 
FOR ALL TO authenticated 
USING (true) 
WITH CHECK (true);

-- Public Read (if needed for storefront but typically restricted)
DROP POLICY IF EXISTS "Global Public Read" ON public.user_permissions;
CREATE POLICY "Global Public Read" ON public.user_permissions 
FOR SELECT TO anon 
USING (true);

-- Audit Columns (Standard for the platform)
ALTER TABLE public.user_permissions ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.user_permissions ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.user_permissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Trigger for updated_at
DROP TRIGGER IF EXISTS trg_set_updated_at ON public.user_permissions;
CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.user_permissions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
