-- =========================================================================
-- FULL ERP & ECOMMERCE SAAS RESET SCRIPT
-- =========================================================================
-- WARNING: This script will DROP all existing tables and recreate them.
-- It ensures consistent ID types (BIGINT for master, UUID for transactional).
-- =========================================================================

-- 0. CLEANUP (Drop tables in reverse order of dependency)
DROP TABLE IF EXISTS public.helpdesk_tickets CASCADE;
DROP TABLE IF EXISTS public.wf_logs CASCADE;
DROP TABLE IF EXISTS public.wf_steps CASCADE;
DROP TABLE IF EXISTS public.wf_workflows CASCADE;
DROP TABLE IF EXISTS public.wa_logs CASCADE;
DROP TABLE IF EXISTS public.hrms_attendance CASCADE;
DROP TABLE IF EXISTS public.hrms_leaves CASCADE;
DROP TABLE IF EXISTS public.hrms_employees CASCADE;
DROP TABLE IF EXISTS public.hrms_departments CASCADE;
DROP TABLE IF EXISTS public.crm_deals CASCADE;
DROP TABLE IF EXISTS public.crm_stages CASCADE;
DROP TABLE IF EXISTS public.crm_pipelines CASCADE;
DROP TABLE IF EXISTS public.contacts CASCADE;
DROP TABLE IF EXISTS public.purchase_bill_items CASCADE;
DROP TABLE IF EXISTS public.purchase_bills CASCADE;
DROP TABLE IF EXISTS public.purchase_order_items CASCADE;
DROP TABLE IF EXISTS public.purchase_orders CASCADE;
DROP TABLE IF EXISTS public.purchase_request_items CASCADE;
DROP TABLE IF EXISTS public.purchase_requests CASCADE;
DROP TABLE IF EXISTS public.sales_invoice_items CASCADE;
DROP TABLE IF EXISTS public.sales_invoices CASCADE;
DROP TABLE IF EXISTS public.sales_order_items CASCADE;
DROP TABLE IF EXISTS public.sales_orders CASCADE;
DROP TABLE IF EXISTS public.sales_quotation_items CASCADE;
DROP TABLE IF EXISTS public.sales_quotations CASCADE;
DROP TABLE IF EXISTS public.headless_configs CASCADE;
DROP TABLE IF EXISTS public.ecom_activities CASCADE;
DROP TABLE IF EXISTS public.ecom_settings CASCADE;
DROP TABLE IF EXISTS public.ecom_menus CASCADE;
DROP TABLE IF EXISTS public.ecom_pages CASCADE;
DROP TABLE IF EXISTS public.payment_gateways CASCADE;
DROP TABLE IF EXISTS public.ecom_order_timeline CASCADE;
DROP TABLE IF EXISTS public.ecom_order_items CASCADE;
DROP TABLE IF EXISTS public.ecom_orders CASCADE;
DROP TABLE IF EXISTS public.ecom_banners CASCADE;
DROP TABLE IF EXISTS public.product_variants CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.brands CASCADE;
DROP TABLE IF EXISTS public.ecom_categories CASCADE;
DROP TABLE IF EXISTS public.company_modules CASCADE;
DROP TABLE IF EXISTS public.system_modules CASCADE;
DROP TABLE IF EXISTS public.company_users CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.companies CASCADE;
DROP TABLE IF EXISTS public.system_plans CASCADE;
DROP TABLE IF EXISTS public.system_templates CASCADE;

-- 1. INFRASTRUCTURE & MULTI-TENANCY
CREATE TABLE public.system_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    price_monthly DECIMAL(12,2) DEFAULT 0,
    price_yearly DECIMAL(12,2) DEFAULT 0,
    features JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subdomain TEXT UNIQUE NOT NULL,
    logo_url TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    gst_no TEXT,
    plan_id BIGINT REFERENCES public.system_plans(id) ON DELETE SET NULL,
    plan TEXT DEFAULT 'starter',
    user_id UUID, -- Owner reference
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    is_super_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.company_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'admin',
    UNIQUE(company_id, user_id)
);

CREATE TABLE public.system_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    is_core BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.company_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    module_id BIGINT REFERENCES public.system_modules(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT true,
    UNIQUE(company_id, module_id)
);

-- 2. MASTER DATA (BIGINT IDs)
CREATE TABLE public.ecom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    sku TEXT,
    category_id BIGINT REFERENCES public.ecom_categories(id) ON DELETE SET NULL,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL,
    rate DECIMAL(12,2) DEFAULT 0,
    price DECIMAL(12,2),
    description TEXT,
    image_url TEXT,
    is_ecommerce BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sku TEXT,
    price DECIMAL(12,2),
    stock_qty INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CONTACT HUB (UUID IDs)
CREATE TABLE public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'customer', -- customer, vendor, lead
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company_name TEXT,
    job_title TEXT,
    status TEXT DEFAULT 'active',
    rating INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SALES MODULE (UUID IDs for Transactions)
CREATE TABLE public.sales_quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.sales_quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id UUID REFERENCES public.sales_quotations(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE public.sales_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE public.sales_invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.sales_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id UUID REFERENCES public.sales_invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

-- 5. PURCHASE MODULE (UUID IDs for Transactions)
CREATE TABLE public.purchase_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.purchase_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID REFERENCES public.purchase_requests(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity DECIMAL(12,2) DEFAULT 1
);

CREATE TABLE public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL, -- Vendor
    vendor_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE public.purchase_bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'draft',
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.purchase_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id UUID REFERENCES public.purchase_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

-- 6. CRM MODULE
CREATE TABLE public.crm_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.crm_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT REFERENCES public.crm_pipelines(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.crm_deals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    stage_id BIGINT REFERENCES public.crm_stages(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. HRMS MODULE
CREATE TABLE public.hrms_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

CREATE TABLE public.hrms_employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    employee_code TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    department_id BIGINT REFERENCES public.hrms_departments(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.hrms_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    status TEXT DEFAULT 'present',
    UNIQUE(employee_id, date)
);

CREATE TABLE public.hrms_leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    status TEXT DEFAULT 'pending'
);

-- 8. COMMUNICATIONS & WORKFLOW
CREATE TABLE public.wa_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    direction TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'sent',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.wf_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    resource TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE public.wf_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE public.wf_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    resource_id UUID NOT NULL,
    step_id BIGINT REFERENCES public.wf_steps(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. HELPDESK
CREATE TABLE public.helpdesk_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open',
    priority TEXT DEFAULT 'medium',
    assigned_to_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. ECOMMERCE CMS & SETTINGS
CREATE TABLE public.ecom_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_number TEXT UNIQUE NOT NULL,
    customer_name TEXT,
    grand_total DECIMAL(12,2) DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.ecom_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INTEGER DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE public.ecom_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content JSONB DEFAULT '[]',
    UNIQUE(company_id, slug)
);

CREATE TABLE public.ecom_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    store_name TEXT,
    config JSONB DEFAULT '{}',
    UNIQUE(company_id)
);

CREATE TABLE public.headless_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    screen_id TEXT NOT NULL,
    section_id TEXT NOT NULL,
    mapping_config JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, screen_id, section_id)
);

-- 11. SECURITY ENGINE (RLS)
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;

-- 12. INITIAL SEED DATA
INSERT INTO public.system_plans (name, slug, price_monthly) VALUES 
('Starter', 'starter', 0),
('Professional', 'professional', 99),
('Enterprise', 'enterprise', 299)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.system_modules (name, is_core) VALUES 
('Ecommerce', true),
('CRM', false),
('Inventory', false),
('HRMS', false),
('Payroll', false),
('WhatsApp', false),
('Helpdesk', false)
ON CONFLICT (name) DO NOTHING;

-- PRESERVE ADMIN USER (Example placeholder - User should run this with their specific ID)
-- INSERT INTO public.users (id, username, full_name, is_super_admin) 
-- VALUES ('<YOUR_ADMIN_ID>', 'admin', 'System Admin', true)
-- ON CONFLICT (username) DO NOTHING;
-- =========================================================================
-- ERP CORE SCHEMA: SALES & PURCHASE MODULES (ERPNext/Odoo Style)
-- =========================================================================
-- This script adds the foundational parent-child table structures 
-- for professional grade ERP operations.

-- -------------------------------------------------------------------------
-- 1. SALES MODULE TABLES
-- -------------------------------------------------------------------------

-- SALES QUOTATIONS (Proposals)
CREATE TABLE IF NOT EXISTS public.sales_quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Created by
    customer_name TEXT NOT NULL,
    customer_email TEXT,
    customer_phone TEXT,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. QUO-2026-001
    date DATE DEFAULT CURRENT_DATE,
    valid_until DATE,
    status TEXT DEFAULT 'draft', -- draft, sent, accepted, rejected, expired
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    notes TEXT,
    terms_and_conditions TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id UUID REFERENCES public.sales_quotations(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(5,2) DEFAULT 0, -- percentage
    amount DECIMAL(12,2) NOT NULL DEFAULT 0, -- (qty * price) + tax
    sort_order INTEGER DEFAULT 0
);

-- SALES ORDERS (Confirmed Sales)
CREATE TABLE IF NOT EXISTS public.sales_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    quotation_id UUID REFERENCES public.sales_quotations(id) ON DELETE SET NULL, -- Link back
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. ORD-2026-001
    date DATE DEFAULT CURRENT_DATE,
    delivery_date DATE,
    status TEXT DEFAULT 'draft', -- draft, on-hold, confirmed, closed, cancelled
    order_status TEXT DEFAULT 'to-deliver', -- to-deliver, delivered, partially-delivered
    billing_status TEXT DEFAULT 'to-invoice', -- to-invoice, invoiced, partially-invoiced
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

-- SALES INVOICES (Billing)
CREATE TABLE IF NOT EXISTS public.sales_invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. INV-2026-001
    date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    status TEXT DEFAULT 'draft', -- draft, unpaid, paid, overdue, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    payment_method TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id UUID REFERENCES public.sales_invoices(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

-- -------------------------------------------------------------------------
-- 2. PURCHASE MODULE TABLES
-- -------------------------------------------------------------------------

-- PURCHASE REQUESTS (Internal Demand)
CREATE TABLE IF NOT EXISTS public.purchase_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. PREQ-2026-001
    date DATE DEFAULT CURRENT_DATE,
    required_by DATE,
    status TEXT DEFAULT 'draft', -- draft, pending-approval, approved, ordered, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID REFERENCES public.purchase_requests(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1
);

-- PURCHASE ORDERS (Vendor Procurement)
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    reference_no TEXT UNIQUE NOT NULL, -- e.g. PUR-ORD-2026-001
    date DATE DEFAULT CURRENT_DATE,
    expected_delivery DATE,
    status TEXT DEFAULT 'draft', -- draft, confirmed, received, closed, cancelled
    total_qty DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- PURCHASE BILLS (Vendor Invoices)
CREATE TABLE IF NOT EXISTS public.purchase_bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    vendor_name TEXT NOT NULL,
    bill_no TEXT NOT NULL, -- Vendor's own bill number
    reference_no TEXT UNIQUE NOT NULL, -- Our internal Ref: BILL-2026-001
    date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    status TEXT DEFAULT 'draft', -- draft, unpaid, paid, overdue
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id UUID REFERENCES public.purchase_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    description TEXT,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- -------------------------------------------------------------------------
-- 3. ENABLE RLS FOR NEW TABLES
-- -------------------------------------------------------------------------
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (
        SELECT tablename FROM pg_tables WHERE schemaname = 'public' 
        AND tablename IN (
            'sales_quotations', 'sales_quotation_items', 'sales_orders', 'sales_order_items',
            'sales_invoices', 'sales_invoice_items', 'purchase_requests', 'purchase_request_items',
            'purchase_orders', 'purchase_order_items', 'purchase_bills', 'purchase_bill_items'
        )
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
-- =========================================================================
-- ERP MODULAR SCHEMA: CRM, HRMS, PAYROLL, WHATSAPP & WORKFLOW
-- =========================================================================

-- 1. CONTACT MANAGEMENT (Unified Hub)
-- Standardizes Customers, Vendors, Leads, and Prospects
CREATE TABLE IF NOT EXISTS public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'customer', -- customer, vendor, lead, prospect
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company_name TEXT,
    job_title TEXT,
    website TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    status TEXT DEFAULT 'active',
    rating INTEGER DEFAULT 0,
    source TEXT, -- internal, web, referral, whatsapp
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CRM MODULE: DEALS & PIPELINES
CREATE TABLE IF NOT EXISTS public.crm_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT REFERENCES public.crm_pipelines(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    probability INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_deals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    stage_id BIGINT REFERENCES public.crm_stages(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    expected_closing DATE,
    priority TEXT DEFAULT 'medium', -- low, medium, high, critical
    status TEXT DEFAULT 'open', -- open, won, lost
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. HRMS MODULE: EMPLOYEES & ATTENDANCE
CREATE TABLE IF NOT EXISTS public.hrms_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    manager_id UUID, -- References users(id) or employees(id) later
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- App Login
    employee_code TEXT UNIQUE NOT NULL, -- e.g. EMP-101
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    department_id BIGINT REFERENCES public.hrms_departments(id) ON DELETE SET NULL,
    designation TEXT,
    date_of_joining DATE DEFAULT CURRENT_DATE,
    date_of_birth DATE,
    gender TEXT,
    blood_group TEXT,
    emergency_contact TEXT,
    status TEXT DEFAULT 'active', -- active, on-leave, resigned, terminated
    salary_basic DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    clock_in TIMESTAMPTZ,
    clock_out TIMESTAMPTZ,
    status TEXT DEFAULT 'present', -- present, absent, half-day, holiday
    ip_address TEXT,
    notes TEXT,
    UNIQUE(employee_id, date)
);

CREATE TABLE IF NOT EXISTS public.hrms_leaves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- sick, casual, annual
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. WHATSAPP & COMMUNICATIONS MODULE
CREATE TABLE IF NOT EXISTS public.wa_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    direction TEXT NOT NULL, -- inbound, outbound
    message TEXT NOT NULL,
    status TEXT DEFAULT 'sent', -- sent, delivered, read, failed
    external_id TEXT, -- Provider ID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. WORKFLOW ENGINE
CREATE TABLE IF NOT EXISTS public.wf_workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    resource TEXT NOT NULL, -- sales_orders, hrms_leaves, etc.
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wf_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    approver_role TEXT, -- admin, manager, etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wf_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    workflow_id BIGINT REFERENCES public.wf_workflows(id) ON DELETE CASCADE,
    resource_id UUID NOT NULL, -- ID of the order/leave/etc
    step_id BIGINT REFERENCES public.wf_steps(id) ON DELETE CASCADE,
    actor_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL, -- approved, rejected, commented
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. HELPDESK MODULE
CREATE TABLE IF NOT EXISTS public.helpdesk_tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT DEFAULT 'medium', -- low, medium, high, critical
    status TEXT DEFAULT 'open', -- open, in-progress, closed, cancelled
    assigned_to_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. SECURITY: RLS FOR MODULAR TABLES
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (
        SELECT tablename FROM pg_tables WHERE schemaname = 'public' 
        AND tablename IN (
            'contacts', 'crm_pipelines', 'crm_stages', 'crm_deals',
            'hrms_departments', 'hrms_employees', 'hrms_attendance', 'hrms_leaves',
            'wa_logs', 'wf_workflows', 'wf_steps', 'wf_logs', 'helpdesk_tickets'
        )
    ) LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
-- =========================================================================
-- ECOMMERCE SAAS: FULL MASTER SCHEMA INIT SCRIPT
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. CORE ARCHITECTURE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    subdomain TEXT UNIQUE NOT NULL,
    logo_url TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    gst_no TEXT,
    plan_id BIGINT, -- Links to system_plans
    plan TEXT DEFAULT 'starter', -- Legacy/Display tier
    plan_slug TEXT, -- Logical plan reference
    industry_type TEXT DEFAULT 'retail',
    user_id UUID, -- Original Creator/Owner
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_plan FOREIGN KEY (plan_id) REFERENCES public.system_plans(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    company_id BIGINT, -- Primary/Default Company
    is_super_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'admin',
    UNIQUE(company_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.system_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL, -- Logical identity node (slug)
    name TEXT NOT NULL,
    tagline TEXT,
    description TEXT,
    icon TEXT DEFAULT '🚀',
    color TEXT DEFAULT '#2563EB',
    color_from TEXT,
    color_to TEXT,
    route TEXT,
    dashboard_route TEXT,
    category TEXT DEFAULT 'operations',
    status TEXT DEFAULT 'live',
    features JSONB DEFAULT '[]', -- Feature Magnitude registry
    included_in_plans JSONB DEFAULT '[]', -- Authorized plans
    needs_template BOOLEAN DEFAULT false,
    is_core BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.company_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Who enabled it
    module_slug TEXT NOT NULL, -- Reference via SLUG for portability
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, module_slug)
);

CREATE TABLE IF NOT EXISTS public.user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    module_slug TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, user_id, module_slug)
);

-- -------------------------------------------------------------------------
-- 2. MASTER DATA TIER
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Creator
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES public.ecom_categories(id) ON DELETE SET NULL,
    brand_id BIGINT REFERENCES public.brands(id) ON DELETE SET NULL,
    category TEXT, -- Legacy compatibility
    sku TEXT,
    rate DECIMAL(12,2) DEFAULT 0,
    price DECIMAL(12,2),
    description TEXT,
    image_url TEXT,
    is_ecommerce BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    is_best_seller BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sku TEXT,
    price DECIMAL(12,2),
    attributes_summary TEXT,
    stock_qty INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    title TEXT,
    subtitle TEXT,
    image_url TEXT NOT NULL,
    position TEXT DEFAULT 'hero',
    badge_text TEXT,
    is_active BOOLEAN DEFAULT true,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 3. ORDERS & FINANCIALS (Strict Audit)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Customer or Creator
    order_number TEXT UNIQUE NOT NULL,
    customer_name TEXT,
    customer_email TEXT,
    customer_phone TEXT,
    shipping_address JSONB DEFAULT '{}',
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax_amount DECIMAL(12,2) DEFAULT 0,
    shipping_amount DECIMAL(12,2) DEFAULT 0,
    discount_amount DECIMAL(12,2) DEFAULT 0,
    grand_total DECIMAL(12,2) DEFAULT 0,
    payment_method TEXT,
    payment_status TEXT DEFAULT 'pending',
    payment_id TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    product_id BIGINT,
    variant_id BIGINT,
    product_name TEXT NOT NULL,
    variant_label TEXT,
    quantity INTEGER DEFAULT 1,
    unit_price DECIMAL(12,2) DEFAULT 0,
    amount DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.ecom_order_timeline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.ecom_orders(id) ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Admin actor
    status TEXT NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payment_gateways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Configuration Admin
    gateway TEXT NOT NULL,
    display_name TEXT,
    is_active BOOLEAN DEFAULT false,
    is_test_mode BOOLEAN DEFAULT true,
    config JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, gateway)
);

-- -------------------------------------------------------------------------
-- 4. WEBSITE MANAGER & CMS (Strictly Assigned)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ecom_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Author
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content JSONB DEFAULT '[]',
    is_published BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, slug)
);

CREATE TABLE IF NOT EXISTS public.ecom_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    label TEXT NOT NULL,
    link_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ecom_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    store_name TEXT,
    store_tagline TEXT,
    logo_url TEXT,
    primary_color TEXT DEFAULT '#000000',
    config JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id)
);

CREATE TABLE IF NOT EXISTS public.ecom_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Active User
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 5. HEADLESS API ARCHITECTURE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.headless_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Integrator
    api_key UUID DEFAULT gen_random_uuid(),
    screen_id TEXT NOT NULL,
    section_id TEXT NOT NULL,
    mapping_config JSONB NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(company_id, screen_id, section_id)
);

-- -------------------------------------------------------------------------
-- 6. SECURITY ENGINE (RLS & IDEMPOTENT POLICIES) - MOVED TO END
-- -------------------------------------------------------------------------

-- -------------------------------------------------------------------------
-- 7. SYSTEM SEED (CORE ONLY)
-- -------------------------------------------------------------------------
INSERT INTO public.system_modules (slug, name, is_core) VALUES 
('ecommerce', 'Ecommerce', true),
('crm', 'CRM', false),
('inventory', 'Inventory', false),
('landing-page', 'Website Manager', true)
ON CONFLICT (slug) DO NOTHING;

-- -------------------------------------------------------------------------
-- 8. PLATFORM TEMPLATES
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    industry TEXT DEFAULT 'multi-purpose',
    version TEXT DEFAULT '1.0.0',
    component_count INTEGER DEFAULT 12,
    preview_image TEXT,
    gallery_images TEXT[] DEFAULT '{}', -- 5 to 10 images for rich preview
    color TEXT,
    tags TEXT[],
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- 9. SUBSCRIPTION & PACKAGE ENGINE
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    price_monthly DECIMAL(12,2) DEFAULT 0,
    price_yearly DECIMAL(12,2) DEFAULT 0,
    features JSONB DEFAULT '[]',
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.system_plans (name, slug, price_monthly, features, sort_order) VALUES 
('Standard', 'standard', 29.00, '["Up to 5 Projects", "Basic Analytics", "Standard Templates", "Email Support"]', 1),
('Professional', 'professional', 99.00, '["Up to 20 Projects", "Advanced Analytics", "Premium Templates", "Priority Support", "Custom Domain"]', 2),
('Enterprise', 'enterprise', 299.00, '["Unlimited Projects", "Full White-label", "Custom Integrations", "Dedicated Account Manager", "SLA Guarantee"]', 3),
('Custom Application', 'custom', 0, '["Tailor-made Architecture", "On-premise Deployment", "Source Code Ownership", "24/7 Elite Support"]', 4)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.system_templates (folder, name, description, industry, version, component_count, preview_image, gallery_images, color, tags, is_active, sort_order) VALUES 
('amazon-style', 'Amazon Style', 'A robust, multi-category layout inspired by the world''s largest e-commerce platform. Best for megastores.', 'retail', '1.0.1', 24, 
 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?q=80&w=900', 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=900', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=900'],
 '#f97316', ARRAY['megastore', 'retail', 'amazon'], true, 1),

('fruitables', 'Fruitables Organic', 'Vibrant, fresh design perfect for organic groceries, fruit shops, and healthy food stores.', 'retail', '1.0.1', 12, 
 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=900', 'https://images.unsplash.com/photo-1466632311177-a3d1433f95e8?q=80&w=900', 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?q=80&w=900'],
 '#81c408', ARRAY['groceries', 'fresh', 'organic'], true, 2),

('modern-shop', 'Modern Shop', 'A sleek, minimalist design suitable for fashion, electronics, and dropshipping brands.', 'retail', '1.0.0', 16, 
 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=900', 
 ARRAY['https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=900', 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=900', 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=900'],
 '#000000', ARRAY['fashion', 'electronics', 'modern'], true, 3)
ON CONFLICT (folder) DO UPDATE SET is_active = EXCLUDED.is_active;

-- -------------------------------------------------------------------------
-- 9. SECURITY ENGINE (RLS & IDEMPOTENT POLICIES)
-- -------------------------------------------------------------------------
-- This ensures ALL tables created in the script above receive global access policies.
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    END LOOP;
END $$;

-- Universal Policy Builder
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        -- Drop global policies if they already exist
        EXECUTE format('DROP POLICY IF EXISTS "Global Full Access" ON public.%I', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Global Public Read" ON public.%I', tbl);
        
        -- Create open authenticated policy
        EXECUTE format('CREATE POLICY "Global Full Access" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
        
        -- Create open anonymous policy for public interactions (like storefront reading products)
        EXECUTE format('CREATE POLICY "Global Public Read" ON public.%I FOR SELECT TO anon USING (true)', tbl);
    END LOOP;
END $$;
-- =========================================================================
-- ULTIMATE ENTERPRISE ERP SAAS SCHEMA (Odoo/ERPNext Style)
-- =========================================================================
-- This script initializes the entire foundation for a multi-tenant
-- enterprise ecosystem including CRM, HRMS, SCM, Finance, and Automation.
-- =========================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- 0. EXTENSIONS & SETUP
-- ─────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────
-- 1. CORE SYSTEM & MULTI-TENANCY
-- ─────────────────────────────────────────────────────────────────────────

-- TENANTS (Top level isolation)
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    subdomain TEXT UNIQUE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COMPANIES (Internal organization nodes)
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    tax_id TEXT,
    logo_url TEXT,
    website TEXT,
    currency_code TEXT DEFAULT 'INR',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- COMPANY BRANCHES
CREATE TABLE IF NOT EXISTS public.company_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT, -- e.g. BR-001
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    phone TEXT,
    is_warehouse BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DEPARTMENTS
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.departments(id),
    name TEXT NOT NULL,
    code TEXT,
    manager_id UUID, -- References users(id) later
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DESIGNATIONS
CREATE TABLE IF NOT EXISTS public.designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    level INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- USERS
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    password_hash TEXT,
    company_id BIGINT REFERENCES public.companies(id),
    branch_id BIGINT REFERENCES public.company_branches(id),
    is_super_admin BOOLEAN DEFAULT false,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ROLES & PERMISSIONS
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module TEXT NOT NULL, -- e.g. 'sales', 'hrms'
    action TEXT NOT NULL, -- e.g. 'create', 'view', 'delete'
    description TEXT,
    UNIQUE(module, action)
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    role_id BIGINT REFERENCES public.roles(id) ON DELETE CASCADE,
    permission_id BIGINT REFERENCES public.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY(role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES public.roles(id) ON DELETE CASCADE,
    PRIMARY KEY(user_id, role_id)
);

-- SYSTEM MANAGEMENT
CREATE TABLE IF NOT EXISTS public.system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB,
    description TEXT
);

CREATE TABLE IF NOT EXISTS public.module_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    module_id TEXT NOT NULL,
    config JSONB DEFAULT '{}',
    is_enabled BOOLEAN DEFAULT true,
    UNIQUE(company_id, module_id)
);

-- LOGGING & AUDIT
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id),
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    resource_id TEXT,
    old_value JSONB,
    new_value JSONB,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 2. CONTACTS HUB (Unified Multi-Role Records)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    type TEXT NOT NULL DEFAULT 'customer', -- customer, vendor, lead, employee
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    tax_id TEXT, -- GST/VAT
    company_name TEXT,
    website TEXT,
    status TEXT DEFAULT 'active',
    rating INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.contact_addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    type TEXT DEFAULT 'billing', -- shipping, billing, outlet
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pincode TEXT,
    is_default BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.contact_bank_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contact_id UUID REFERENCES public.contacts(id) ON DELETE CASCADE,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    branch_name TEXT,
    is_default BOOLEAN DEFAULT false
);

-- ─────────────────────────────────────────────────────────────────────────
-- 3. PRODUCTS & UOM MATRIX
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.uom_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.uoms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.uom_categories(id),
    name TEXT NOT NULL,
    ratio DECIMAL(12,4) DEFAULT 1.0, -- Relative to base UOM
    type TEXT DEFAULT 'bigger' -- smaller, reference, bigger
);

CREATE TABLE IF NOT EXISTS public.product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.product_categories(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL,
    uom_id BIGINT REFERENCES public.uoms(id),
    name TEXT NOT NULL,
    sku TEXT,
    barcode TEXT,
    type TEXT DEFAULT 'storable', -- storable, consumable, service
    description TEXT,
    image_url TEXT,
    standard_rate DECIMAL(15,2) DEFAULT 0, -- Cost
    sales_price DECIMAL(15,2) DEFAULT 0,
    weight DECIMAL(12,2),
    volume DECIMAL(12,2),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    sku TEXT,
    barcode TEXT,
    price_extra DECIMAL(15,2) DEFAULT 0,
    stock_qty DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 4. INVENTORY & WAREHOUSING
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES public.company_branches(id),
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    location_type TEXT DEFAULT 'internal',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stock_moves (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    reference_no TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL, -- incoming, outgoing, internal, adjustment
    warehouse_from_id BIGINT REFERENCES public.warehouses(id),
    warehouse_to_id BIGINT REFERENCES public.warehouses(id),
    status TEXT DEFAULT 'draft', -- draft, processed, cancelled
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.stock_move_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    move_id UUID REFERENCES public.stock_moves(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL,
    uom_id BIGINT REFERENCES public.uoms(id),
    lot_no TEXT,
    serial_no TEXT
);

-- ─────────────────────────────────────────────────────────────────────────
-- 5. SALES & CRM (Revenue Engine)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sales_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Client
    branch_id BIGINT REFERENCES public.company_branches(id),
    reference_no TEXT UNIQUE NOT NULL, -- e.g. SO-2026-0001
    date DATE DEFAULT CURRENT_DATE,
    expected_delivery DATE,
    status TEXT DEFAULT 'draft', -- draft, confirmed, invoiced, delivered, cancelled
    subtotal DECIMAL(15,2) DEFAULT 0,
    tax_amount DECIMAL(15,2) DEFAULT 0,
    discount_amount DECIMAL(15,2) DEFAULT 0,
    grand_total DECIMAL(15,2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.sales_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────
-- 6. PURCHASE (Procurement Cycle)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Vendor
    branch_id BIGINT REFERENCES public.company_branches(id),
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    expected_receipt DATE,
    status TEXT DEFAULT 'draft', -- draft, ordered, received, billed, cancelled
    grand_total DECIMAL(15,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    quantity DECIMAL(15,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    amount DECIMAL(15,2) NOT NULL DEFAULT 0
);

-- ─────────────────────────────────────────────────────────────────────────
-- 7. ACCOUNTING & FINANCE
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.accounts_chart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES public.accounts_chart(id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- asset, liability, equity, income, expense
    is_group BOOLEAN DEFAULT false,
    balance DECIMAL(15,2) DEFAULT 0,
    UNIQUE(company_id, code)
);

CREATE TABLE IF NOT EXISTS public.journals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    reference_no TEXT UNIQUE NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    type TEXT DEFAULT 'general', -- sales, purchase, cash, bank
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_id UUID REFERENCES public.journals(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES public.accounts_chart(id),
    contact_id UUID REFERENCES public.contacts(id),
    debit DECIMAL(15,2) DEFAULT 0,
    credit DECIMAL(15,2) DEFAULT 0,
    memo TEXT
);

-- ─────────────────────────────────────────────────────────────────────────
-- 8. HRMS & PAYROLL
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_salary_structures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    base_salary DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.hrms_employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Linked to unified contacts
    employee_code TEXT UNIQUE NOT NULL,
    department_id BIGINT REFERENCES public.departments(id),
    designation_id BIGINT REFERENCES public.designations(id),
    salary_structure_id BIGINT REFERENCES public.payroll_salary_structures(id),
    joining_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 9. PROJECTS & TASKS
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id), -- Client
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    start_date DATE,
    end_date DATE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to UUID REFERENCES public.users(id),
    priority TEXT DEFAULT 'medium',
    status TEXT DEFAULT 'todo',
    due_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 10. WORKFLOW ENGINE
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.workflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL, -- sales_orders, purchase_orders, hrms_leaves
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.workflow_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT REFERENCES public.workflows(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    required_role_id BIGINT REFERENCES public.roles(id)
);

CREATE TABLE IF NOT EXISTS public.approval_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL,
    resource_id UUID NOT NULL,
    workflow_id BIGINT REFERENCES public.workflows(id),
    current_step_id BIGINT REFERENCES public.workflow_steps(id),
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 11. SECURITY & RLS ENFORCEMENT
-- ─────────────────────────────────────────────────────────────────────────

DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Tenant Isolation Policy" ON public.%I', tbl);
        
        -- Global policy: Authenticated users can see records 
        -- Real production logic would check company_id/tenant_id 
        -- But for this MVP infrastructure, we enable full access to authenticated roles
        EXECUTE format('CREATE POLICY "Tenant Isolation Policy" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- 12. INITIAL SYSTEM SEED
-- ─────────────────────────────────────────────────────────────────────────

-- Base UOMs
INSERT INTO public.uom_categories (name) VALUES ('Unit'), ('Weight'), ('Volume'), ('Time') ON CONFLICT DO NOTHING;
INSERT INTO public.uoms (category_id, name, ratio, type) VALUES 
((SELECT id FROM uom_categories WHERE name='Unit'), 'Nos', 1.0, 'reference'),
((SELECT id FROM uom_categories WHERE name='Weight'), 'Kg', 1.0, 'reference'),
((SELECT id FROM uom_categories WHERE name='Weight'), 'Gram', 0.001, 'smaller'),
((SELECT id FROM uom_categories WHERE name='Time'), 'Hour', 1.0, 'reference')
ON CONFLICT DO NOTHING;

-- Base Permissions
INSERT INTO public.permissions (module, action) VALUES 
('sales', 'create'), ('sales', 'view'), ('sales', 'delete'), ('sales', 'approve'),
('purchase', 'create'), ('purchase', 'view'), ('purchase', 'delete'),
('hrms', 'create'), ('hrms', 'view'),
('finance', 'create'), ('finance', 'post')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- 13. WHATSAPP & META INTEGRATION (Bulk Messaging & Campaigns)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.whatsapp_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone_number_id TEXT NOT NULL,
    access_token TEXT NOT NULL,
    verify_token TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    whatsapp_account_id UUID REFERENCES public.whatsapp_accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- marketing, utility, authentication
    language TEXT DEFAULT 'en_US',
    components JSONB NOT NULL, -- Header, Body, Footer, Buttons
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    meta_template_id TEXT, -- Template ID from Meta
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    template_id UUID REFERENCES public.whatsapp_templates(id),
    audience_filter JSONB, -- Criteria for target contacts
    status TEXT DEFAULT 'draft', -- draft, scheduled, running, completed
    scheduled_at TIMESTAMPTZ,
    stats JSONB DEFAULT '{"sent": 0, "delivered": 0, "read": 0, "failed": 0}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.whatsapp_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    contact_id UUID REFERENCES public.contacts(id),
    campaign_id UUID REFERENCES public.whatsapp_campaigns(id),
    message_sid TEXT,
    status TEXT, -- sent, delivered, read, failed
    payload JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 14. HRMS EXTENSIONS: INDUCTION & ONBOARDING
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.hrms_induction_protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hrms_onboarding_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_id BIGINT REFERENCES public.hrms_induction_protocols(id) ON DELETE CASCADE,
    task_name TEXT NOT NULL,
    mandatory BOOLEAN DEFAULT true,
    order_index INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.hrms_employee_induction (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id UUID REFERENCES public.hrms_employees(id) ON DELETE CASCADE,
    protocol_id BIGINT REFERENCES public.hrms_induction_protocols(id),
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed
    completion_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 15. PAYROLL ENGINE & PAYSLIPS
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- earning, deduction
    calculation_type TEXT NOT NULL, -- flat, percentage
    value DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.payroll_payslips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.hrms_employees(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    basic_salary DECIMAL(15,2) DEFAULT 0,
    gross_earnings DECIMAL(15,2) DEFAULT 0,
    total_deductions DECIMAL(15,2) DEFAULT 0,
    net_salary DECIMAL(15,2) DEFAULT 0,
    status TEXT DEFAULT 'draft', -- draft, processed, paid, cancelled
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 16. E-COMMERCE & CATALOG MASTERS (Brands, Attributes, Variants)
-- ─────────────────────────────────────────────────────────────────────────

-- BRANDS
CREATE TABLE IF NOT EXISTS public.product_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    logo_url TEXT,
    website TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- SUB-BRANDS
CREATE TABLE IF NOT EXISTS public.product_sub_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT REFERENCES public.product_brands(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ATTRIBUTES (Size, Color, Material, etc.)
CREATE TABLE IF NOT EXISTS public.product_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- e.g. 'Color'
    display_type TEXT DEFAULT 'text', -- text, swatches, dropdown
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ATTRIBUTE VALUES (Red, XL, Silk, etc.)
CREATE TABLE IF NOT EXISTS public.product_attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id BIGINT REFERENCES public.product_attributes(id) ON DELETE CASCADE,
    value TEXT NOT NULL, -- e.g. 'Red'
    meta_data JSONB, -- e.g. {"hex": "#FF0000"}
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LINK PRODUCTS TO BRANDS
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS brand_id BIGINT REFERENCES public.product_brands(id);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sub_brand_id BIGINT REFERENCES public.product_sub_brands(id);

-- PRODUCT REVIEWS (Consumer Feedback Node)
CREATE TABLE IF NOT EXISTS public.product_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    is_verified_purchase BOOLEAN DEFAULT false,
    status TEXT DEFAULT 'pending', -- pending, approved, hidden
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LINK VARIANTS TO ATTRIBUTE VALUES
CREATE TABLE IF NOT EXISTS public.product_variant_attribute_values (
    variant_id BIGINT REFERENCES public.product_variants(id) ON DELETE CASCADE,
    attribute_value_id BIGINT REFERENCES public.product_attribute_values(id) ON DELETE CASCADE,
    PRIMARY KEY(variant_id, attribute_value_id)
);

-- RE-RUN RLS ENFORCEMENT LOOP
DO $$ 
DECLARE
    tbl TEXT;
BEGIN
    FOR tbl IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Tenant Isolation Policy" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Tenant Isolation Policy" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);
    END LOOP;
END $$;
