// ============================================================================
// Database TypeScript Interfaces
// Auto-mapped from: database/saas_tables.sql + database/migration_v2_complete.sql
// ============================================================================

// ---------------------------------------------------------------------------
// Platform Root: SaaS Multi-Tenant Foundation
// ---------------------------------------------------------------------------

export interface Company {
  id: number; // BIGINT GENERATED BY DEFAULT AS IDENTITY
  name?: string;
  subdomain?: string;
  industry_type?: string;
  tax_number?: string;
  contact_email?: string;
  contact_phone?: string;
  address?: string;
  user_id?: string;
  created_at?: string;
  updated_at?: string;
}

export interface User {
  id: string; // UUID
  username?: string;
  full_name?: string;
  avatar_url?: string;
  is_super_admin?: boolean;
  company_id?: number;
  created_at?: string;
  updated_at?: string;
}

export interface CompanyUser {
  id: string; // UUID
  company_id: number;
  user_id?: string;
  role?: string;
  status?: string;
  created_at?: string;
}

export interface UserPermission {
  id: string; // UUID
  company_user_id?: string;
  resource?: string;
  action?: string;
}

// ---------------------------------------------------------------------------
// 1. Master Hub: Shared Registry (Tenant-Isolated)
// ---------------------------------------------------------------------------

export interface MasterContact {
  id: string; // UUID
  company_id: number;
  full_name?: string;
  type?: string;
  email?: string;
  phone?: string;
  gst_number?: string;
  pan?: string;
  billing_address?: string;
  shipping_address?: string;
  erp_id?: string;
  status?: string;
  user_id?: string;
  created_at?: string;
  updated_at?: string;
}

export interface MasterContactPerson {
  id: string; // UUID
  company_id: number;
  contact_id?: string;
  contact_person?: string;
  phone?: string;
  email?: string;
  role?: string;
  created_at?: string;
}

export interface MasterCategory {
  id: string; // UUID
  company_id: number;
  parent_id?: string;
  name?: string;
  type?: string;
  description?: string;
  is_active?: boolean;
  sort_order?: number;
  url_key?: string;
  visibility?: string;
  ecom_mapping?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterBrand {
  id: string; // UUID
  company_id: number;
  name?: string;
  sub_brand_name?: string;
  description?: string;
  is_active?: boolean;
  priority?: number;
  seo_keyword?: string;
  visibility?: string;
  api_mapping?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterItem {
  id: string; // UUID
  company_id: number;
  item_name?: string;
  item_code?: string;
  item_type?: string;
  usage_unit?: string;
  category_id?: string;
  brand_id?: string;
  hsn_sac?: string;
  status?: string;
  purchase_price?: number;
  mrp?: number;
  selling_price?: number;
  gst_rate?: number;
  discount_eligible?: boolean;
  tax_group_id?: string;
  is_live?: boolean;
  web_title?: string;
  seo_description?: string;
  featured?: boolean;
  weight_kg?: number;
  default_warehouse_id?: string;
  reorder_level?: number;
  min_stock?: number;
  max_stock?: number;
  image_url?: string;
  description?: string;
  current_stock?: number;
  user_id?: string;
  created_at?: string;
  updated_at?: string;
}

export interface MasterProductVariant {
  id: string; // UUID
  company_id: number;
  item_id?: string;
  name?: string;
  sku?: string;
  barcode?: string;
  description?: string;
  price_adjustment?: number;
  is_active?: boolean;
  erp_variant_id?: string;
  visibility?: string;
  stock_qty?: number;
  user_id?: string;
  created_at?: string;
}

export interface MasterProductReview {
  id: string; // UUID
  company_id: number;
  item_id?: string;
  customer_id?: string;
  rating?: number;
  comment?: string;
  status?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterUom {
  id: string; // UUID
  company_id: number;
  name?: string;
  category?: string;
  reference_uom?: string;
  ratio?: number;
  is_active?: boolean;
  precision?: number;
  erp_uom_code?: string;
  visibility?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterTax {
  id: string; // UUID
  company_id: number;
  tax_name?: string;
  tax_type?: string;
  rate?: number;
  description?: string;
  applies_to?: string;
  status?: string;
  account_code?: string;
  hsn_sac?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterAttribute {
  id: string; // UUID
  company_id: number;
  name?: string;
  type?: string;
  unit?: string;
  description?: string;
  is_filterable?: boolean;
  is_required?: boolean;
  display_type?: string;
  erp_mapping_id?: string;
  visibility?: string;
  is_active?: boolean;
  user_id?: string;
  created_at?: string;
}

export interface MasterChartOfAccount {
  id: string; // UUID
  company_id: number;
  account_code?: string;
  account_name?: string;
  account_type?: string;
  parent_account_id?: string;
  is_group?: boolean;
  notes?: string;
  is_active?: boolean;
  user_id?: string;
  created_at?: string;
}

export interface MasterFiscalYear {
  id: string; // UUID
  company_id: number;
  name?: string;
  start_date?: string;
  end_date?: string;
  is_active?: boolean;
  user_id?: string;
  created_at?: string;
}

export interface MasterPriceList {
  id: string; // UUID
  company_id: number;
  name?: string;
  currency?: string;
  type?: string;
  is_active?: boolean;
  effective_from?: string;
  effective_to?: string;
  erp_mapping_id?: string;
  visibility?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterSkuPattern {
  id: string; // UUID
  company_id: number;
  name?: string;
  prefix?: string;
  suffix?: string;
  counter_start?: number;
  digits?: number;
  separator?: string;
  is_active?: boolean;
  erp_mapping_id?: string;
  visibility?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterRole {
  id: string; // UUID
  company_id: number;
  name?: string;
  scope?: string;
  description?: string;
  permission_flags?: string;
  is_active?: boolean;
  external_role_map?: string;
  group_alias?: string;
  user_id?: string;
  created_at?: string;
}

export interface MasterUser {
  id: string; // UUID
  company_id: number;
  full_name?: string;
  email?: string;
  phone?: string;
  role?: string;
  password?: string;
  is_active?: boolean;
  mfa_enabled?: boolean;
  department_id?: string;
  erp_user_ref?: string;
  user_id?: string;
  created_at?: string;
}

// ---------------------------------------------------------------------------
// 2. Sales Module
// ---------------------------------------------------------------------------

export interface SalesQuotation {
  id: string; // UUID
  company_id: number;
  created_by?: string;
  quote_number?: string;
  customer_id?: string;
  date?: string;
  valid_until?: string;
  total_amount?: number;
  status?: string;
  user_id?: string;
  created_at?: string;
}

export interface SalesQuotationItem {
  id: string; // UUID
  company_id: number;
  quotation_id?: string;
  item_id?: string;
  quantity?: number;
  rate?: number;
  total?: number;
}

export interface SalesOrder {
  id: string; // UUID
  company_id: number;
  created_by?: string;
  order_number?: string;
  order_date?: string;
  contact_id?: string;
  subtotal?: number;
  tax_amount?: number;
  grand_total?: number;
  status?: string;
  billing_address?: string;
  shipping_address?: string;
  created_at?: string;
  updated_at?: string;
}

export interface SalesOrderItem {
  id: string; // UUID
  company_id: number;
  order_id?: string;
  item_id?: string;
  quantity?: number;
  unit_price?: number;
  tax_id?: string;
  tax_amount?: number;
  line_total?: number;
}

export interface SalesInvoice {
  id: string; // UUID
  company_id: number;
  created_by?: string;
  invoice_number?: string;
  invoice_date?: string;
  due_date?: string;
  contact_id?: string;
  sales_order_id?: string;
  subtotal?: number;
  tax_amount?: number;
  grand_total?: number;
  status?: string;
  created_at?: string;
  updated_at?: string;
}

export interface SalesInvoiceItem {
  id: string; // UUID
  company_id: number;
  invoice_id?: string;
  item_id?: string;
  quantity?: number;
  unit_price?: number;
  tax_id?: string;
  tax_amount?: number;
  line_total?: number;
}

// ---------------------------------------------------------------------------
// 3. Purchase Module
// ---------------------------------------------------------------------------

export interface PurchaseRequest {
  id: string; // UUID
  company_id: number;
  requested_by?: string;
  request_name?: string;
  date?: string;
  required_by_date?: string;
  status?: string;
  created_at?: string;
}

export interface PurchaseOrder {
  id: string; // UUID
  company_id: number;
  po_number?: string;
  po_date?: string;
  contact_id?: string;
  subtotal?: number;
  tax_amount?: number;
  grand_total?: number;
  status?: string;
  user_id?: string;
  created_at?: string;
}

export interface PurchaseReceipt {
  id: string; // UUID
  company_id: number;
  grn_number?: string;
  receipt_date?: string;
  po_id?: string;
  contact_id?: string;
  status?: string;
  user_id?: string;
  created_at?: string;
}

export interface PurchaseBill {
  id: string; // UUID
  company_id: number;
  grn_id?: string;
  supplier_id?: string;
  bill_number?: string;
  date?: string;
  total_amount?: number;
  status?: string;
  user_id?: string;
  created_at?: string;
}

// ---------------------------------------------------------------------------
// 4. E-Commerce Module
// ---------------------------------------------------------------------------

export interface EcomOrder {
  id: string; // UUID
  company_id: number;
  user_id?: string;
  order_number?: string;
  customer_name?: string;
  customer_email?: string;
  customer_phone?: string;
  shipping_address?: Record<string, any>;
  billing_address?: Record<string, any>;
  subtotal?: number;
  tax_amount?: number;
  shipping_amount?: number;
  discount_amount?: number;
  coupon_code?: string;
  payment_method?: string;
  payment_status?: string;
  payment_id?: string;
  status?: string;
  tracking_number?: string;
  courier_name?: string;
  grand_total?: number;
  created_at?: string;
  updated_at?: string;
}

export interface EcomOrderItem {
  id: string; // UUID
  order_id?: string;
  company_id: number;
  product_id?: string;
  variant_id?: string;
  product_name?: string;
  variant_name?: string;
  image_url?: string;
  quantity?: number;
  unit_price?: number;
  amount?: number;
  price_at_time?: number;
  total_price?: number;
  created_at?: string;
}

export interface EcomBanner {
  id: string; // UUID
  company_id: number;
  title?: string;
  subtitle?: string;
  badge_text?: string;
  button_text?: string;
  button_link?: string;
  image_url?: string;
  position?: string;
  display_order?: number;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface EcomSettings {
  id: string; // UUID
  company_id: number;
  logo_url?: string;
  favicon_url?: string;
  store_name?: string;
  store_tagline?: string;
  primary_color?: string;
  contact_email?: string;
  contact_phone?: string;
  address?: string;
  facebook_url?: string;
  instagram_url?: string;
  twitter_url?: string;
  whatsapp_number?: string;
  footer_text?: string;
  currency?: string;
  gst_number?: string;
  meta_title?: string;
  meta_description?: string;
  created_at?: string;
  updated_at?: string;
}

export interface PaymentGateway {
  id: string; // UUID
  company_id: number;
  gateway?: string;
  display_name?: string;
  is_active?: boolean;
  is_test_mode?: boolean;
  config?: Record<string, any>;
  created_at?: string;
  updated_at?: string;
}

export interface Coupon {
  id: string; // UUID
  company_id: number;
  code?: string;
  description?: string;
  type?: string;
  value?: number;
  min_order_amount?: number;
  max_discount?: number;
  usage_limit?: number;
  per_user_limit?: number;
  usage_count?: number;
  valid_from?: string;
  valid_until?: string;
  is_active?: boolean;
  created_at?: string;
  updated_at?: string;
}

// ---------------------------------------------------------------------------
// 5. CRM Module
// ---------------------------------------------------------------------------

export interface CrmDeal {
  id: string; // UUID
  company_id: number;
  lead_id?: string;
  contact_id?: string;
  stage_id?: number;
  deal_name?: string;
  title?: string;
  amount?: number;
  expected_closing?: string;
  priority?: string;
  stage?: string;
  status?: string;
  notes?: string;
  user_id?: string;
  created_at?: string;
  updated_at?: string;
}

export interface CrmPipeline {
  id: number; // BIGINT GENERATED BY DEFAULT AS IDENTITY
  company_id: number;
  name?: string;
  is_default?: boolean;
  created_at?: string;
}

// ---------------------------------------------------------------------------
// 7. Inventory Module
// ---------------------------------------------------------------------------

export interface Warehouse {
  id: string; // UUID
  company_id: number;
  name?: string;
  location?: string;
  is_active?: boolean;
  created_at?: string;
}

export interface StockLedger {
  id: number; // BIGINT GENERATED BY DEFAULT AS IDENTITY
  company_id: number;
  product_id?: number;
  warehouse_id?: number;
  qty_in?: number;
  qty_out?: number;
  balance_qty?: number;
  valuation_rate?: number;
  reference_type?: string;
  reference_id?: string;
  posting_date?: string;
  created_at?: string;
}

export interface StockEntry {
  id: string; // UUID
  company_id: number;
  user_id?: string;
  reference_no?: string;
  entry_type?: string;
  from_warehouse_id?: number;
  to_warehouse_id?: number;
  posting_date?: string;
  reference_doc_type?: string;
  reference_doc_id?: string;
  status?: string;
  total_value?: number;
  notes?: string;
  created_at?: string;
  updated_at?: string;
}

export interface StockEntryItem {
  id: number; // BIGINT GENERATED BY DEFAULT AS IDENTITY
  entry_id?: string;
  product_id?: number;
  item_code?: string;
  description?: string;
  uom?: string;
  qty?: number;
  basic_rate?: number;
  basic_amount?: number;
  batch_no?: string;
  serial_no?: string;
  sort_order?: number;
}

// ---------------------------------------------------------------------------
// 8. HRMS Module
// ---------------------------------------------------------------------------

export interface HrmsEmployee {
  id: string; // UUID
  company_id: number;
  employee_code?: string;
  full_name?: string;
  department_id?: string;
  designation?: string;
  status?: string;
  user_id?: string;
  created_at?: string;
}

// ---------------------------------------------------------------------------
// Table Name Union Type
// ---------------------------------------------------------------------------

export type TableName =
  | "companies"
  | "users"
  | "company_users"
  | "user_permissions"
  | "master_contacts"
  | "master_contact_persons"
  | "master_categories"
  | "master_subcategories"
  | "master_brands"
  | "master_uoms"
  | "master_taxes"
  | "master_items"
  | "master_product_variants"
  | "master_product_reviews"
  | "master_chart_of_accounts"
  | "master_fiscal_years"
  | "master_price_lists"
  | "master_sku_patterns"
  | "master_attributes"
  | "master_roles"
  | "master_users"
  | "sales_quotations"
  | "sales_quotation_items"
  | "sales_orders"
  | "sales_order_items"
  | "sales_invoices"
  | "sales_invoice_items"
  | "purchase_requests"
  | "purchase_orders"
  | "purchase_receipts"
  | "purchase_bills"
  | "ecom_orders"
  | "ecom_order_items"
  | "ecom_banners"
  | "ecom_settings"
  | "payment_gateways"
  | "coupons"
  | "crm_leads"
  | "crm_deals"
  | "crm_pipelines"
  | "inventory_warehouses"
  | "stock_ledger"
  | "stock_entries"
  | "stock_entry_items"
  | "stock_levels"
  | "stock_moves"
  | "hrms_employees"
  | "hrms_departments"
  | "pos_sessions"
  | "pos_orders"
  | "whatsapp_accounts"
  | "whatsapp_templates"
  | "whatsapp_logs"
  | "whatsapp_contacts"
  | "whatsapp_campaigns"
  | "whatsapp_campaign_messages"
  | "whatsapp_conversations"
  | "whatsapp_messages"
  | "whatsapp_bot_rules"
  | "receipt_vouchers"
  | "finance_journal_entries"
  | "finance_bank_accounts"
  // Website CMS
  | "web_media"
  | "web_templates"
  | "web_page_sections"
  | "web_components"
  | "web_forms"
  | "web_form_submissions"
  | "web_seo_meta"
  | "web_content_versions"
  // Website Business Engine
  | "web_groups"
  | "web_registrations"
  | "web_schedules"
  | "web_pricing"
  | "web_pricing_items"
  | "web_payments"
  | "web_credentials"
  // Website Custom Fields
  | "web_custom_field_defs"
  // Website Advanced
  | "web_events"
  | "web_event_registrations"
  | "web_testimonials"
  | "web_automation_rules"
  | "web_api_keys"
  | "web_translations";
