import type { DocTypeDef } from "../types";

export const webCustomFieldDef: DocTypeDef = {
  name: "Custom Field",
  tableName: "web_custom_field_defs",
  module: "website",
  showItems: false,

  headerFields: [
    { key: "target_table", label: "Target Screen", type: "select", required: true, options: [
      { value: "web_groups", label: "Groups" },
      { value: "web_registrations", label: "Registrations" },
      { value: "web_schedules", label: "Schedules" },
      { value: "web_pricing", label: "Pricing Plans" },
      { value: "web_payments", label: "Payments" },
      { value: "web_credentials", label: "Credentials" },
      { value: "web_events", label: "Events" },
      { value: "web_event_registrations", label: "Event Registrations" },
      { value: "web_testimonials", label: "Testimonials" },
      { value: "web_enquiries", label: "Enquiries" },
      { value: "web_pages", label: "Web Pages" },
      { value: "blog_posts", label: "Blog Posts" },
      { value: "web_forms", label: "Forms" },
      { value: "gallery_items", label: "Gallery" },
      { value: "web_faqs", label: "FAQs" },
      { value: "web_media", label: "Media" },
      { value: "web_templates", label: "Templates" },
      { value: "web_components", label: "Components" },
      { value: "master_items", label: "Items (Masters)" },
      { value: "master_contacts", label: "Contacts (Masters)" },
      { value: "sales_orders", label: "Sales Orders" },
      { value: "sales_invoices", label: "Sales Invoices" },
      { value: "sales_quotations", label: "Sales Quotations" },
      { value: "purchase_orders", label: "Purchase Orders" },
      { value: "purchase_bills", label: "Purchase Bills" },
      { value: "crm_leads", label: "CRM Leads" },
      { value: "crm_deals", label: "CRM Deals" },
      { value: "crm_accounts", label: "CRM Accounts" },
      { value: "hrms_employees", label: "Employees" },
      { value: "ecom_orders", label: "E-Commerce Orders" },
    ]},
    { key: "field_key", label: "Field Key", type: "text", required: true, placeholder: "e.g. blood_group (no spaces, lowercase)" },
    { key: "field_label", label: "Display Label", type: "text", required: true, placeholder: "e.g. Blood Group" },
    { key: "field_type", label: "Field Type", type: "select", required: true, options: [
      { value: "text", label: "Text" },
      { value: "number", label: "Number" },
      { value: "date", label: "Date" },
      { value: "select", label: "Dropdown" },
      { value: "checkbox", label: "Checkbox" },
      { value: "textarea", label: "Text Area" },
      { value: "email", label: "Email" },
      { value: "phone", label: "Phone" },
      { value: "currency", label: "Currency" },
    ]},
    { key: "placeholder", label: "Placeholder", type: "text" },
    { key: "default_value", label: "Default Value", type: "text" },
    { key: "options", label: "Dropdown Options", type: "textarea", placeholder: '[{"value":"A+","label":"A Positive"},{"value":"B+","label":"B Positive"}]' },
    { key: "is_required", label: "Required", type: "checkbox" },
    { key: "is_visible", label: "Visible", type: "checkbox" },
    { key: "section", label: "Form Section", type: "select", options: [
      { value: "basic", label: "Basic Info" },
      { value: "config", label: "Configuration" },
      { value: "custom", label: "Custom Fields" },
    ]},
    { key: "sort_order", label: "Sort Order", type: "number" },
  ],

  columns: [
    { key: "target_table", label: "Screen" },
    { key: "field_key", label: "Key" },
    { key: "field_label", label: "Label" },
    { key: "field_type", label: "Type" },
    { key: "is_required", label: "Required" },
    { key: "is_visible", label: "Visible" },
    { key: "sort_order", label: "Order" },
  ],

  searchableFields: ["target_table", "field_key", "field_label"],
  defaults: { is_visible: true, is_required: false, section: "custom", sort_order: 0, field_type: "text" },
};
