import { useState, useEffect } from "react";
import {
    ShoppingCart, Search, Plus,
    MoreHorizontal, Mail, Download,
    Trash2, Clock, CheckCircle2,
    Filter, ArrowRight, Eye, Edit,
    Truck, FileInput
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import { useTenant } from "@/contexts/TenantContext";
import ERPEntryForm from "@/components/modules/ERPEntryForm";
import ERPListView, { StatusBadge } from "@/components/modules/ERPListView";
import { useLocation, useNavigate } from "react-router-dom";

export default function Orders() {
    const [view, setView] = useState<"list" | "form">("list");
    const [searchTerm, setSearchTerm] = useState("");
    const [orders, setOrders] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [editingOrder, setEditingOrder] = useState<any>(null);
    const [editingItems, setEditingItems] = useState<any[] | undefined>(undefined);
    const { activeCompany } = useTenant();
    const location = useLocation();
    const navigate = useNavigate();

    useEffect(() => {
        if (activeCompany) loadOrders();
    }, [activeCompany]);

    // Relational Workflow Engine: Catch incoming Conversions (Quotation -> Sales Order)
    useEffect(() => {
        const processIncomingConversion = async () => {
            if (location.state?.conversionType === 'quotation_to_so' && location.state?.sourceRecord) {
                const quote = location.state.sourceRecord;
                
                // Fetch the line items from the quotation
                const { data: quoteItems } = await supabase
                    .from('sales_quotation_items')
                    .select('*')
                    .eq('quotation_id', quote.id);

                const mappedItems = (quoteItems || []).map(item => ({
                    description: item.description,
                    quantity: item.quantity,
                    unitPrice: item.unit_price,
                    taxRate: item.tax_rate,
                    amount: item.amount
                }));

                setEditingOrder({
                    customer_name: quote.customer_name,
                    reference_no: `SO-${quote.reference_no.replace('QT-', '')}`,
                    date: new Date().toISOString().split('T')[0],
                    status: 'draft',
                    notes: `Autogenerated from Quotation: ${quote.reference_no}`
                });
                
                if (mappedItems.length > 0) setEditingItems(mappedItems);
                
                setView("form");
                // Clear the state so refresh doesn't trigger reapplying the conversion
                window.history.replaceState({}, document.title);
            }
        };
        processIncomingConversion();
    }, [location.state]);

    const loadOrders = async () => {
        if (!activeCompany) return;
        setLoading(true);
        const { data, error } = await supabase
            .from('sales_orders')
            .select('*')
            .eq('company_id', activeCompany.id)
            .order('created_at', { ascending: false });

        if (!error && data) setOrders(data);
        setLoading(false);
    };

    const orderHeaderFields = [
        { key: "customer_name", label: "Customer", required: true, ph: "Customer name..." },
        { key: "reference_no", label: "Order Reference", required: true, ph: "ORD-2026-001" },
        { key: "date", label: "Order Date", type: "date" as const },
        { key: "delivery_date", label: "Delivery Date", type: "date" as const },
        {
            key: "status", label: "Status", type: "select" as const,
            options: [
                { label: "Draft", value: "draft" },
                { label: "On-Hold", value: "on-hold" },
                { label: "Confirmed", value: "confirmed" },
                { label: "Closed", value: "closed" }
            ]
        }
    ];

    const handleSaveOrder = async (header: any, items: any[]) => {
        try {
            const totalQty = items.reduce((sum, i) => sum + i.quantity, 0);
            const subtotal = items.reduce((sum, i) => sum + (i.quantity * i.unitPrice), 0);
            const taxAmount = items.reduce((sum, i) => sum + (i.quantity * i.unitPrice * i.taxRate / 100), 0);
            const grandTotal = subtotal + taxAmount;

            const payload = {
                ...header,
                company_id: activeCompany?.id,
                total_qty: totalQty,
                subtotal: subtotal,
                tax_amount: taxAmount,
                grand_total: grandTotal
            };

            const { data: savedHeader, error: hError } = await supabase
                .from('sales_orders')
                .upsert([payload])
                .select()
                .single();

            if (hError) throw hError;

            if (header.id) {
                await supabase.from('sales_order_items').delete().eq('order_id', header.id);
            }

            const lineItems = items.map(item => ({
                order_id: savedHeader.id,
                description: item.description,
                quantity: item.quantity,
                unit_price: item.unitPrice,
                tax_percentage: item.taxRate, // Mapping taxRate to tax_percentage in DB
                amount: item.amount
            }));

            const { error: iError } = await supabase.from('sales_order_items').insert(lineItems);
            if (iError) throw iError;

            toast.success("Sales Order Saved");
            setView("list");
            loadOrders();
        } catch (err: any) {
            toast.error(`Save Failed: ${err.message}`);
        }
    };

    const filteredOrders = orders.filter(o =>
        o.customer_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        o.reference_no?.toLowerCase().includes(searchTerm.toLowerCase())
    );

    const fmt = (n: number) => `₹${Number(n || 0).toLocaleString("en-IN")}`;

    const handleConvertToInvoice = () => {
        navigate("/apps/sales/invoices", { 
            state: { 
                sourceRecord: editingOrder, 
                conversionType: 'so_to_invoice' 
            } 
        });
    };

    if (view === "form") {
        return (
            <div className="p-8 animate-in fade-in slide-in-from-bottom-5 duration-500">
                <ERPEntryForm
                    title={editingOrder ? "Edit Sales Order" : "New Sales Order"}
                    subtitle="Manage customer orders and shipments"
                    headerFields={orderHeaderFields}
                    onAbort={() => { setView("list"); setEditingOrder(null); setEditingItems(undefined); }}
                    onSave={handleSaveOrder}
                    initialData={editingOrder}
                    initialItems={editingItems || (editingOrder ? [] : undefined)}
                    customActions={
                        editingOrder && editingOrder.id && (
                            <button
                                onClick={handleConvertToInvoice}
                                className="flex items-center h-9 px-4 text-xs font-bold bg-indigo-50 text-indigo-700 hover:bg-indigo-100 rounded-xl transition-all shadow-sm border border-indigo-100"
                            >
                                <ArrowRight className="w-3.5 h-3.5 mr-2" />
                                Generate Invoice
                            </button>
                        )
                    }
                />
            </div>
        );
    }

    const orderColumns = [
        { 
            key: "reference_no", 
            label: "Order ID",
            render: (o: any) => <span className="font-bold text-gray-900 tracking-tight ">{o.reference_no}</span>
        },
        { 
            key: "customer_name", 
            label: "Customer",
            render: (o: any) => (
                <div className="flex flex-col">
                    <span className="font-bold text-gray-800">{o.customer_name}</span>
                    <span className="text-xs text-gray-400 font-bold  tracking-widest">{o.date || 'No Date'}</span>
                </div>
            )
        },
        { 
            key: "grand_total", 
            label: "Total Amount",
            render: (o: any) => <span className="font-bold text-blue-600 tracking-tight">{fmt(o.grand_total)}</span>,
            className: "text-right"
        },
        { 
            key: "status", 
            label: "Status",
            render: (o: any) => <StatusBadge status={o.status} />
        }
    ];

    return (
        <ERPListView
            title="Sales Orders"
            data={filteredOrders}
            columns={orderColumns}
            onNew={() => { setEditingOrder(null); setView("form"); }}
            onRefresh={loadOrders}
            onRowClick={(o) => { setEditingOrder(o); setView("form"); }}
            isLoading={loading}
            searchTerm={searchTerm}
            onSearchChange={setSearchTerm}
            primaryKey="id"
        />
    );
}
